### ISSUE TITLE
39 of the algorithms from the book are not implemented yet

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aimacode/aima-python#1]
```
Need to implement the missing algorithms.
```

Original issue reported on code.google.com by `peter.no...@gmail.com` on 15 Jun 2007 at 7:39

**Comment by hkhats95** [comment]
Hello, Dr. Norvig
I would like to contribute in writing algorithms in python.
Could please tell me how to contribute to it.

Regards,
Hitesh

**Comment by TusharGupta01** [comment]
Hi,
I would like to work on Reinforcement Learning and Neural Networks implementation as a part of gsoc 2016. Please give your insite. 

Thanks
Tushar Gupta
Indian Institute of Technology Mandi, India

**Comment by Payal94** [comment]
Hey Norvig, 

@norvig 
I would like to implement algorithms from the book which are not yet implemented. I will start from implementing [topological_sort](https://github.com/aimacode/aima-python/blob/master/aimaPy/csp.py#L335) and [make_arc_consistency](https://github.com/aimacode/aima-python/blob/master/aimaPy/csp.py#L339) functions.

**Comment by norvig** [comment]
You should all be able to find some work to do by looking at the list of functions on the home page readme file. Thanks for your efforts.

**Comment by rusrushal13** [comment]
Hello,
I would like to implement algorithms from the book which are not yet implemented.
Could you please tell me the algorithms which are not implemented yet?
It will be great help.
Regards,
Rushal Verma

**Comment by SnShine** [comment]
Hey,
You can go through https://github.com/aimacode/aima-python#index-of-code of readme to see unimplemented algorithms.
