### ISSUE TITLE
Erro while running py.test

### ISSUE THREAD

**Issue by ThuriyaThwin** [aimacode/aima-python#1027]
py.test
============================= test session starts ==============================
platform linux2 -- Python 2.7.15rc1, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/thuriyathwin/aima-python, inifile: pytest.ini
collected 0 items / 14 errors

**Comment by sagar-sehgal** [comment]
@ThuriyaThwin It seems that you are running the code in python 2.7. But the system is made to run for Python3.4 and up. It has been mentioned [here](https://github.com/aimacode/aima-python#python-34-and-up).

**Comment by abhinavsagar** [comment]
I think the issue is with Python 2.
This is only supported in Python 3.
