### ISSUE TITLE
Regarding inline doctests

### ISSUE THREAD

**Issue by SnShine** [aimacode/aima-python#103]
For learners, I think inline doctests serve as clean examples of what that particular method is doing. I don't think it is really good to remove doctests which are located in docs of each method; we can have all the doctests at *_test.py. 

@norvig a decision need to be taken if we want to keep doctests in each method or not.

**Comment by gokul-uf** [comment]
refer issue #74

**Comment by SnShine** [comment]
Yeah, I have seen that and I have submitted a PR #66 (changes only utils.py) which is merged. But, now I am having second thoughts if we want to leave some doctests which can serve as examples for learners.

**Comment by norvig** [comment]
Good point. I think there are two purposes of tests: examples, and true tests. 

For functions where it is not immediately obvious how to use them, it would be good to have exactly one example in the docstring.  For example:

def product(numbers):
    """Return the product of the numbers.
    >>> product([2, 3, 4])
    24"""

What we don't want is a long collection of true tests in the docstring that cover all the corner cases (one number, no numbers, zeroes, etc.).

**Comment by norvig** [comment]
I've updated the README.md to reflect @SnShine 's idea of "leave some doctests which can serve as examples for learners."
