### ISSUE TITLE
Import statements in try-except block

### ISSUE THREAD

**Issue by rajatjain1997** [aimacode/aima-python#1030]
In `agents.py` I stumbled onto the following import statements:

https://github.com/aimacode/aima-python/blob/e9033cf7a46478a8af93831784695a68c128e165/agents.py#L577-L582

These import statements are used to render graphics by the `GraphicEnvironment` class defined just below it. However, since these packages are not mentioned in `requirements.txt`, neither binder nor any developer installs them before running the notebooks. This results in the following stacktrace when `agents.ipynb` tries to create an instance of `GraphicEnvironment`:

```

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-18-0a21d3807079> in <module>
----> 1 park = GraphicPark(5,5, color={'EnergeticBlindDog': (200,0,0), 'Water': (0, 200, 200), 'Food': (230, 115, 40)})
      2 dog = EnergeticBlindDog(program)
      3 dogfood = Food()
      4 water = Water()
      5 park.add_thing(dog, [0,0])

/spare/aimacode/agents.py in __init__(self, width, height, boundary, color, display)
    588         but initialise a BlockGrid for GUI too."""
    589         super().__init__(width, height)
--> 590         self.grid = BlockGrid(width, height, fill=(200, 200, 200))
    591         if display:
    592             self.grid.show()

NameError: name 'BlockGrid' is not defined 
```
There are two ways to resolve this issue:
 - Remove the statements from the try except block and include these packages in `requirements.txt`
 - Put the entire class `GraphicEnvironment` in try-except so that it is only defined if those packages are installed.

I prefer the first approach since it requires minimal changes and because the second one will lead to the class not working on binder at all. However since the contribution guide states that no new packages should be added to `requirements.txt`, I'm at an impasse.

**Steps to reproduce the issue:**
 - Open Binder > agents.ipynb
 - Rerun all cells by restarting the kernel (This is required because the initial output is a cached version by the notebook)

**Comment by dshahid380** [comment]
I would like to take this issue.

**Comment by rajatjain1997** [comment]
Umm... My PR already works on solving the issue.

**Comment by dshahid380** [comment]
But you did not get murge right.

**Comment by ad71** [comment]
#1031 will be merged soon @dshahid380 .
This issue will be closed as soon as that is done. Till then, consider this resolved.

**Comment by gamechanger98** [comment]
i would like to work on this issue as I am also having it.

**Comment by rajatjain1997** [comment]
I know you are using Pycharm/Spyder. You can just ignore the error by installing the required dependencies using pip. PR #1031 solves this issue and would be merged soon.
