### ISSUE TITLE
[Query/suggestion] While loop in cross_validation_wrapper

### ISSUE THREAD

**Issue by DeepKumai** [aimacode/aima-python#1049]
So the reason no one is working on the issue of while loop in **cross_validation _wrapper** is because we are still not clear about the functionality of cross validation? Because if not, then isn't it a simple break or return statement after the if statement will break the loop after converging.

**Comment by SiluPanda** [comment]
What do you exactly mean by 'converging' ?
Also, as much I understand, the protocol is, the code should closely follow the pseudocode in the book, unless confirmed by @norvig sir.
So my guess is, people are waiting for an update from sir, or a change in the pseudocode in the book.

**Comment by DeepKumai** [comment]
https://github.com/aimacode/aima-python/blob/5e5b51c47a6573c636c424e67bcae8dbbbebc87e/learning.py#L1101-L1104
The if condition from above snippet is to check for convergence (new error is extremely close to previous error). This is what i meant by 'converging'.

So there is no use in working on cross validation until there is an update.

**Comment by SiluPanda** [comment]
The convergence is checked on training error, and then, best size if determined according to the minimum validation error, as it is in the book. 
Refer [this](https://github.com/aimacode/aima-pseudocode/blob/master/md/Cross-Validation-Wrapper.md) to see the pseudocode which is followed in the code.
I hope I'm able to clarify this.
