### ISSUE TITLE
TODO's in agent.py

### ISSUE THREAD

**Issue by jeff3456** [aimacode/aima-python#107]
**NO LONGER WORKING ON THIS IGNORE REST OF THIS MESSAGE**

Hey I just wanted to create this issue to let you all know that I'm finishing up the todos in agent.py

I will also be adding examples in the iPython notebook for the agents.py .

**Comment by reachtarunhere** [comment]
Hi! I have already worked on moving the doctests so you can leave that little part.

**Comment by tolusalako** [comment]
@jeff3456 are you still working on it? I could help out since I need the Wumpus environment to finish the agents.ipynb I started.

**Comment by anuj1995** [comment]
In case of any help i would like to work on it as i have similar work already

**Comment by jeff3456** [comment]
@tolusalako and @anuj1995 Feel free to work on it yourselves! I have gotten sidetracked and am no longer working on this.

**Comment by anuj1995** [comment]
thanks for the reply

**Comment by tolusalako** [comment]
@anuj1995 I'm almost done with all the todo's in agents.py. You can find most of my updates here: #169
