### ISSUE TITLE
module 'matplotlib.pyplot' has no attribute 'ishold'

### ISSUE THREAD

**Issue by pupinello** [aimacode/aima-python#1087]
Hi

When I run 
show_map(romania_graph_data)
in search.ipynb, the search notbook I get this message:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-059e9091fc22> in <module>
----> 1 show_map(romania_graph_data)

~/notebook.py in show_map(graph_data, node_colors)
    916     # draw the graph (both nodes and edges) with locations from romania_locations
    917     nx.draw(G, pos={k: node_positions[k] for k in G.nodes()},
--> 918             node_color=[node_colors[node] for node in G.nodes()], linewidths=0.3, edgecolors='k')
    919 
    920     # draw labels for nodes

/srv/conda/envs/notebook/lib/python3.7/site-packages/networkx/drawing/nx_pylab.py in draw(G, pos, ax, hold, **kwds)
    124     if 'with_labels' not in kwds:
    125         kwds['with_labels'] = 'labels' in kwds
--> 126     b = plt.ishold()
    127     # allow callers to override the hold state by passing hold=True|False
    128     h = kwds.pop('hold', None)

AttributeError: **module 'matplotlib.pyplot' has no attribute 'ishold'**

I am running on the binder environment

Thanks
Pub

**Comment by Sreyan88** [comment]
Hi @pupinello ,
There are two ways I know of through which you can solve this error. You can either downgrade matplotlib to 2.2.3 or you can upgrade networkx package. In the latest version of networkx the issue might have been solved as I don't see the following lines of code there.

**Comment by Sreyan88** [comment]
Hi @pupinello ,
There are two ways I know of through which you can solve this error. You can either downgrade matplotlib to 2.2.3 or you can upgrade networkx package. Upgrading networkx to 2.3 worked for me. Just follow:
pip uninstall networkx
pip install networkx

Thanks
