### ISSUE TITLE
probability.ipynb: enumeration_ask and elimination_ask runtime comparison wrong

### ISSUE THREAD

**Issue by alessandrocuda** [aimacode/aima-python#1098]
By running **probability.ipynb** I noticed an error in the result of **Runtime comparison** between `enumeration_ask` and `elimination_ask` algorithms.
In the notebook is reported that:
> We observe that variable elimination was faster than enumeration as we had expected...

but by running the code you get the opposite result:

```
%%timeit -n 1000
enumeration_ask('Burglary', dict(JohnCalls=True, MaryCalls=True), burglary).show_approx()
# 104 µs ± 26.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

```
%%timeit -n 1000
elimination_ask('Burglary', dict(JohnCalls=True, MaryCalls=True), burglary).show_approx()
# 243 µs ± 19.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by ad71** [comment]
Hi @alessandrocuda I am responsible for this. When I was working on this, I wrote the results I got, but I can't explain this. Maybe it has something to do with number of threads and how python tries to optimize things, or maybe it is version-specific? I'm sorry I don't know what happened.

**Comment by alessandrocuda** [comment]
Thank you very much for the quick reply @ad71 . I'm investigating why this happens but it could be any one of those listed, at least it might be an idea to update the comparison on the notebook in a formal way? I could open a pull request and update the section with this information

elimination_ask should be a optimization of enumeration_ask but the complexity of some operations requires attention:

- `sum_out` and `pointwise_product` function used in elimination_ask is where space and time complexity arise in the variable elimination algorithm (AIMA3e pg. 526) (look at the profiler result [profiler_result.txt](https://github.com/aimacode/aima-python/files/3502587/profiler_result.txt))

- Elimination ordering is important, in this case the algorithm apply a reversed order (AIMA3e pg. 527)

-  An optimization (AIMA3e pg. 528) is to remove 'every variable that is not an ancestor of a query variable or evidence variable as it is irrelevant to the query' (i.e. sums to 1). 

- The subset of variables from the Bayesian Network to be retained after irrelevant hidden variables have been removed.

**Comment by ad71** [comment]
Sure, that will be very helpful. Thanks!
