### ISSUE TITLE
Is there a Davis-Putnam Algorithm Implemented?

### ISSUE THREAD

**Issue by Locate929** [aimacode/aima-python#1128]
Hi friends,

I checked out the list and I did not see anything for Davis-Putnam for Python (https://en.wikipedia.org/wiki/Davis–Putnam_algorithm). Is it already added or will it be added?

Thanks

**Comment by DonatoMeoli** [comment]
It is already implemented in logic.py as `dpll_satisfiable`

**Comment by Locate929** [comment]
@DonatoMeoli Ahh okay, very quick question though: Is there a difference between Davis Putnam & Davis–Putnam–Logemann–Loveland algorithms?

They kind of look the same but im not 100% sure

**Comment by DonatoMeoli** [comment]
DPLL = DP (only backtracking search) + unit clause propagation heurisic + pure literal heuristic
