### ISSUE TITLE
Why not use a numpy style python docstrings

### ISSUE THREAD

**Issue by tirthasheshpatel** [aimacode/aima-python#1140]
It would be great to have the numpy style documentation for the classes and functions in this project! Currently, it's quite difficult to understand the implemented functions and utilities...
Something like this would be great:
```
class Agent(Thing):
    """
    Parameters
    ----------
    program: :type:`function` , default=None
              The program of the agent.

    Attributes
    ----------
    alive: `boolean`
            Boolean indicating if the agent is alive.
    
    bump: `boolean`
            Boolean indicating weather the agent is
            bumping into anything.
    
    holding: `list`
            A list of all the `Things` that the agent
            is holding.
    
    performance: `numbers.Number`
            A number indicating the performance of the agent.

    program: `function` or `lambda`
            A function invoked whenever a new percept arrives.
            returns action
    
    can_grab: ``Not implemented yet!``
    """

    def __init__(self, program=None):
        self.alive = True
        self.bump = False
        self.holding = []
        self.performance = 0
        if program is None or not isinstance(program, collections.Callable):
            print("Can't find a valid program for {}, falling back to default.".format(
                self.__class__.__name__))

            def program(percept):
                return eval(input('Percept={}; action? '.format(percept)))

        self.program = program

    def can_grab(self, thing):
        """Return True if this agent can grab this thing.
        Override for appropriate subclasses of Agent and Thing."""
        return False


def TraceAgent(agent):
    """Wrap the agent's program to print its input and output. This will let
    you see what the agent is doing in the environment."""
    old_program = agent.program

    def new_program(percept):
        action = old_program(percept)
        print('{} perceives {} and does {}'.format(agent, percept, action))
        return action

    agent.program = new_program
    return agent
```

**Comment by whitten** [comment]
I agree that it would be good to increase documentation. I'm concerned because students and new programmers are heavy contributors to this project.   How standard are these forms of annotation/docstrings ?

**Comment by tirthasheshpatel** [comment]
> How standard are these forms of annotation/docstrings ?

They are used in most of the scientific modules for python and have great readability. Further contributions would become much easier for an experienced python developer working with scientific libraries as well as for beginners who are new to python.

> Will this put an additional burden on people with limited time and education ?

It's a very wide question and may have many viewpoints! As of now, many new developers are looking ahead to contribute to this project and documentation is a great way to start to learn and contribute at the same time. Hence, new developers may find it quite inspiring and motivating as a starting point to their open-source journey but I doubt any of the experienced developers would invest a lot of time in it...

> If you started doing this, would there be a problem knowing which ones are accurate ?

This is a big task to carry out. To get 100% accuracy on the first try is far from possible. But the documentation would definitely get better with time and the support of the community.

> YOu didn't mention any @tags would they facilitate testing ?

Numpy style of docstrings is quite different and I doubt there are much @tags (except @author and some more) to it. The docstrings are quite readable due to the removal of such tags and addition of titles like:
```
<describe the class or method or function>
Parameters
---------
...

Returns
------
...

Attributes
---------
...

Examples
--------
...

Notes
-----
...

See Also
------
...
```

Coming to your last question: yes, there are tools to test numpy style docstrings using [pydocstyle](https://github.com/PyCQA/pydocstyle/pull/226)

**Comment by antmarakis** [comment]
I don't disagree with this style, but I think it is a bit too much for a project such as this. Even though there is no concrete documentation guide for this project, what we generally want to do to avoid cluttering the scripts is to only add details for variables/functions that are not easy to understand. Remember that this project is based on a book, so in a way a lot of the documentation/background for the functions can be found in the book.

I think it will be best if we keep documentation fluid here. For simpler functions/classes, there is no need to go in depth, but for more complicating items we should use more details (for example, as found in [the Dataset class in learning](https://github.com/aimacode/aima-python/blob/master/learning.py#L13l) ).

Feel free to add more detail to any parts of the documentation that need it, that would be greatly appreciated. :)

**Comment by darius** [comment]
Note that CONTRIBUTING.md says

> I prefer more concise docstrings; I don't follow [Pep 257](https://www.python.org/dev/peps/pep-0257/). In most cases,
a one-line docstring suffices. It is rarely necessary to list what each argument does; the name of the argument usually is enough.

Sometimes it's helpful to say more about a parameter than may be obvious from the name; usually then we'd say this in the form of a paragraph documenting what the function does, referring to each parameter at a point natural to the explanation instead of breaking them out in bullets in parameter order. (Where 'we' means the authors some years ago when I was more active here.)

There are some advantages to the bulleted style, but it tends to make the documentation overwhelm the code, which can make it *harder* to read the code + docs.

Since this is already covered in CONTRIBUTING.md I think we should close this issue.

**Comment by tirthasheshpatel** [comment]
Oh sorry! I wasn't following this for a long time. I will close this. Thanks for clarification @darius!
