### ISSUE TITLE
Add support for all types of problems in Bidirectional Search

### ISSUE THREAD

**Issue by tirthasheshpatel** [aimacode/aima-python#1144]
Bidirectional search currently only supports `GraphProblem` type problems. I think we can add support for all the problem types by storing the nodes instead of states in open/closed list for both directions and calling `n.expand(problem)` on it to return the next states.

**Comment by antmarakis** [comment]
I have responded to the PR as well, but I think this would be a worthwhile addition if you could make it work for general problems, thanks!
