### ISSUE TITLE
 ModuleNotFoundError: No module named 'ipythonblocks'

### ISSUE THREAD

**Issue by kgreed** [aimacode/aima-python#1181]
I ran the install instructions.
When I type py.test I get the following output
![image](https://user-images.githubusercontent.com/1795966/75647745-06fe2e00-5ca2-11ea-8152-aa1888ef0a76.png)

The full error message is 
 
`________________________________________ ERROR collecting tests/test_agents.py ________________________________________
ImportError while importing test module 'D:\python\aima-python\tests\test_agents.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_agents.py:5: in <module>
    from agents import (ReflexVacuumAgent, ModelBasedVacuumAgent, TrivialVacuumEnvironment, compare_agents,
agents.py:39: in <module>
    from ipythonblocks import BlockGrid
E   ModuleNotFoundError: No module named 'ipythonblocks'
_______________________________________ ERROR collecting tests/test_agents4e.py _______________________________________
ImportError while importing test module 'D:\python\aima-python\tests\test_agents4e.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_agents4e.py:5: in <module>
    from agents4e import (ReflexVacuumAgent, ModelBasedVacuumAgent, TrivialVacuumEnvironment, compare_agents,
agents4e.py:39: in <module>
    from ipythonblocks import BlockGrid
E   ModuleNotFoundError: No module named 'ipythonblocks'
_________________________________________ ERROR collecting tests/test_csp.py __________________________________________
ImportError while importing test module 'D:\python\aima-python\tests\test_csp.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_csp.py:3: in <module>
    from csp import *
csp.py:11: in <module>
    from sortedcontainers import SortedSet
E   ModuleNotFoundError: No module named 'sortedcontainers'
___________________________________ ERROR collecting tests/test_deep_learning4e.py ____________________________________
ImportError while importing test module 'D:\python\aima-python\tests\test_deep_learning4e.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_deep_learning4e.py:2: in <module>
    from keras.datasets import imdb
E   ModuleNotFoundError: No module named 'keras'
______________________________________ ERROR collecting tests/test_knowledge.py _______________________________________
ImportError while importing test module 'D:\python\aima-python\tests\test_knowledge.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_knowledge.py:3: in <module>
    from knowledge import *
knowledge.py:10: in <module>
    from logic import (FolKB, constant_symbols, predicate_symbols, standardize_variables,
logic.py:40: in <module>
    import networkx as nx
E   ModuleNotFoundError: No module named 'networkx'
_______________________________________ ERROR collecting tests/test_learning.py _______________________________________
ImportError while importing test module 'D:\python\aima-python\tests\test_learning.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_learning.py:3: in <module>
    from learning import *
learning.py:7: in <module>
    from qpsolvers import solve_qp
E   ModuleNotFoundError: No module named 'qpsolvers'
______________________________________ ERROR collecting tests/test_learning4e.py ______________________________________
ImportError while importing test module 'D:\python\aima-python\tests\test_learning4e.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_learning4e.py:3: in <module>
    from deep_learning4e import PerceptronLearner
deep_learning4e.py:7: in <module>
    from keras import Sequential, optimizers
E   ModuleNotFoundError: No module named 'keras'
________________________________________ ERROR collecting tests/test_logic.py _________________________________________
ImportError while importing test module 'D:\python\aima-python\tests\test_logic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_logic.py:3: in <module>
    from logic import *
logic.py:40: in <module>
    import networkx as nx
E   ModuleNotFoundError: No module named 'networkx'
_____________________________________ ERROR collecting tests/test_perception4e.py _____________________________________
ImportError while importing test module 'D:\python\aima-python\tests\test_perception4e.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_perception4e.py:5: in <module>
    from perception4e import *
perception4e.py:3: in <module>
    import cv2
E   ModuleNotFoundError: No module named 'cv2'
_______________________________________ ERROR collecting tests/test_planning.py _______________________________________
ImportError while importing test module 'D:\python\aima-python\tests\test_planning.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_planning.py:5: in <module>
    from planning import *
planning.py:11: in <module>
    from csp import sat_up, NaryCSP, Constraint, ac_search_solver, is_constraint
csp.py:11: in <module>
    from sortedcontainers import SortedSet
E   ModuleNotFoundError: No module named 'sortedcontainers'
________________________________ ERROR collecting tests/test_probabilistic_learning.py ________________________________
ImportError while importing test module 'D:\python\aima-python\tests\test_probabilistic_learning.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_probabilistic_learning.py:5: in <module>
    from learning import DataSet
learning.py:7: in <module>
    from qpsolvers import solve_qp
E   ModuleNotFoundError: No module named 'qpsolvers'
_____________________________________ ERROR collecting tests/test_probability.py ______________________________________
ImportError while importing test module 'D:\python\aima-python\tests\test_probability.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_probability.py:3: in <module>
    from probability import *
probability.py:6: in <module>
    from agents import Agent
agents.py:39: in <module>
    from ipythonblocks import BlockGrid
E   ModuleNotFoundError: No module named 'ipythonblocks'
================================================== warnings summary ===================================================
csp.py:1268
  D:\python\aima-python\csp.py:1268: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if isinstance(assignment[var], set) and len(assignment[var]) is 1:

csp.py:1396
  D:\python\aima-python\csp.py:1396: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if isinstance(assignment[var], set) and len(assignment[var]) is 1:

search.py:1253
  D:\python\aima-python\search.py:1253: SyntaxWarning: "is not" with a literal. Did you mean "!="?
    if state[-1] is not -1:

search.py:1281
  D:\python\aima-python\search.py:1281: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if state[-1] is -1:

tests\test_search.py:229
  D:\python\aima-python\tests\test_search.py:229: SyntaxWarning: "is not" with a literal. Did you mean "!="?
    if len(plan) is not 2:

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 12 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================== 5 warnings, 12 errors in 3.76s ============================================
`

**Comment by tirthasheshpatel** [comment]
Hey @kgreed, did you run ``pip install -r requirements.txt`` on your local computer? If you are still facing some problem with the installation, you can create a virtual environment and install all the requirements there.
For windows, use ``python -m venv env`` to create a environment ``env`` and then activate it using ``.\env\Scripts\activate``. For linux, use ``source ./env/bin/activate`` to activate your environment. Than you can run ``pip install requirements.txt`` on any machine.

**Comment by kgreed** [comment]
Thanks @tirthasheshpatel  the only requirement I did not have installed was tensorflow I assumed that I would not need that just yet.

**Comment by kgreed** [comment]
Looks like my problem installing tensorflow is [because I have python 3.9](https://github.com/tensorflow/tensorflow/issues/33374)

**Comment by kgreed** [comment]
I realised that it was odd to think I needed bs 2019 so I removed the path variables and consulted [the wiki](https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F) Then I ran 

`install --upgrade setuptools
pip install -r requirements.txt
`
here is the error message

```
   Running setup.py install for quadprog ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\kirst\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kirst\\AppData\\Local\\Temp\\pip-install-ozb8rkc4\\quadprog\\setup.py'"'"'; __file__='"'"'C:\\Users\\kirst\\AppData\\Local\\Temp\\pip-install-ozb8rkc4\\quadprog\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kirst\AppData\Local\Temp\pip-record-gkjmbohe\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kirst\appdata\local\programs\python\python37\Include\quadprog'
         cwd: C:\Users\kirst\AppData\Local\Temp\pip-install-ozb8rkc4\quadprog\
    Complete output (60 lines):
    running install
    running build
    running build_ext
    cythoning quadprog/quadprog.pyx to quadprog\quadprog.cpp
    c:\users\kirst\appdata\local\programs\python\python37\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\kirst\AppData\Local\Temp\pip-install-ozb8rkc4\quadprog\quadprog\quadprog.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    building 'quadprog' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\kirst\AppData\Local\Temp\pip-install-ozb8rkc4\quadprog\setup.py", line 60, in <module>
        ext_modules=extensions,
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
        _build_ext.run(self)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\command\build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\_msvccompiler.py", line 346, in compile
        self.initialize()
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\distutils\_msvccompiler.py", line 239, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\site-packages\setuptools\msvc.py", line 1623, in return_env
        if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
      File "c:\users\kirst\appdata\local\programs\python\python37\lib\genericpath.py", line 30, in isfile
        st = os.stat(path)
    TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\kirst\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kirst\\AppData\\Local\\Temp\\pip-install-ozb8rkc4\\quadprog\\setup.py'"'"'; __file__='"'"'C:\\Users\\kirst\\AppData\\Local\\Temp\\pip-install-ozb8rkc4\\quadprog\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kirst\AppData\Local\Temp\pip-record-gkjmbohe\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kirst\appdata\local\programs\python\python37\Include\quadprog' Check the logs for full command output.
```

**Comment by kgreed** [comment]
The error message seems to be to do with missing similar to [this issue](https://github.com/pypa/setuptools/issues/1902)

**Comment by kgreed** [comment]
I changed visual studio 19 to have all C++ development enabled
I also realised that I had not followed @tirthasheshpatel properly, I had missed running 
`.\env\Scripts\activate`

I have now managed to run 

pip install -r requirements.txt successfully.

**Comment by kgreed** [comment]
I then re did the whole install process without creating the env
it worked and the tests all passed.  To summarise I think the issues were do do with needing Python 3.7 and installing C++ development environment.

**Comment by antmarakis** [comment]
Thanks for the troubleshooting! It is unfortunate that the dependency list has ballooned, hopefully a solution will be found...

**Comment by minhduc01168** [comment]
I ran the install instructions.
When I type py.test I get the following output 
![Screenshot from 2022-09-20 01-00-07](https://user-images.githubusercontent.com/81012512/191085399-072404b5-ade8-4152-afff-de46ff9e042b.png)

**Comment by Fabianjavi45** [comment]
Did you get fix this? I'm currently experiencing this error, but only on tests/test_perception4e.py

**Comment by Fabianjavi45** [comment]
Hey @minhduc01168 Did you get fix this? I'm currently experiencing this error, but only on tests/test_perception4e.py
