### ISSUE TITLE
AIMA 3rd edition region/country questions

### ISSUE THREAD

**Issue by datatalking** [aimacode/aima-python#1237]
So I am prepping the many details for a PhD and this book is on the reading list but a friend of mine has a roommate who finished hers and gave me about $600 in books which I thought was great.

Now as I read through them they all say  "this edition only for use or for sale in India, Bangladesh, Bhutan, Pakistan, Nepal, Sri Lanka, and the Maldives" which is concerning because my PhD is in the United States where I need to have the full version which I was hoping this was.

I understand that the 4th edition is set to come out soon but is ISBN 978-93-325-4351-5 soft cover with a robot hand playing chess on an otherwise creme background. This is likely the version I have, found a link on amazon. https://www.amazon.in/Artificial-Intelligence-3e-Modern-Approach/dp/9332543518

1. Is this book 100% normal edition and that's just a "legalese" note from publishing lawyers for copyright?
2. What (if anything) gets changed for the India edition?
3. Can I bridge those gaps with supplemental material here?

I look forward to contributing to the group, as I've been reading a first edition hard copy and had to take a few years of algebra just to catch up to get to the calculus.

**Comment by reachtarunhere** [comment]
Yep the book has the same content. Only difference would be in paper/print quality and whether it is color or black and white edition.
