### ISSUE TITLE
Python 3.4; isclose; --max-line-length 100

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-python#130]
I have set the build to use Python 3.4, because there was a report of the container system failing to load Python 3.5 sometimes.  The only feature of 3.5 that we were using was math.isclose; I implemented it as utils.isclose, so if you want to use isclose (probably in tests), import it from utils, not math.

I set --max-line-length 100 in flake8.

**Comment by anuj1995** [comment]
In my merge request i updated the code accordingly
