### ISSUE TITLE
Failure of verify_query from tests/test_text.py on Windows

### ISSUE THREAD

**Issue by chiragvartak** [aimacode/aima-python#131]
The [pytestlog.txt](https://github.com/aimacode/aima-python/files/170943/pytestlog.txt) attached is self-explanatory. The problem caused is due to Windows using backslashes instead of forward slashes in fie path names.  
Also, note that Travis cannot catch such errors, as, by default, Travis runs the code on Linux. Travis also supports code testing on Mac but not on Windows. Well, we can't do anything about this sadly.  
Hence, just a note to developers on Windows: Make sure to run pytest on your machine before creating a pull request.

**Comment by norvig** [comment]
We can't easily run on windows, but we can make the test compare only file names, not full path, probably with 

```
assert os.path.basename(expected.url) == os.path.basename(doc.url)
```
