### ISSUE TITLE
Recursive_Best_First_Search problem

### ISSUE THREAD

**Issue by Jsevillamol** [aimacode/aima-python#177]
I am currently trying to implement some algorithms in the book, and when I was testing **Recursive Best-First Search** I found an instance of the 15-puzzle with a 32 steps long solution for which it seems that RBFS fails miserably, in the sense that it has been running for six hours or so and has not found a solution yet, while A* provides a solution in seconds.

Wondering whether I had made a mistake in the implementation, I copy pasted the code from this repo (with some small modifications) and ran it on the instance, but the results are the same.

The details of the instance and a solution are in the following file
[15-puzzle hard instance.txt](https://github.com/aimacode/aima-python/files/191184/15-puzzle.hard.instance.txt).

Bug or example of weird edge case in which RBFS has a terrible time performance compared to A*?

**EDIT:** Forgot to mention that the heuristic I am using is Manhattan distance.

**Comment by norvig** [comment]
RBFS saves space, but can take more time. But it acts similarly to IDA*, in that normally the time is proportional to the number of times you need to update, which is bounded by 32 for each state, so imy guess is that it shouldn't take that long. Make sure that you are updating the path costs appropriately. Make sure you do not allow paths with loops in them. You might want to look at the aima-java project, or some other implementation of RBFS.

**Comment by Jsevillamol** [comment]
I'm still a bit baffled by the other instance, but I moved on, modified the algorithm to not consider loopy paths and plotted and analyzed the performance in [this article](https://www.overleaf.com/read/vwwtyfgtjztv).

Turns out that checking for loops is a bigger improvement than what I initially though!

**Comment by SnShine** [comment]
Closing as this is resolved. Comment if I am mistaken.
