### ISSUE TITLE
%pylab deprecated

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-python#187]
The[ matplotlib docs](http://matplotlib.org/faq/usage_faq.html#matplotlib-pyplot-and-pylab-how-are-they-related) says

> Although many examples use `%pylab`, it is no longer recommended.

Instead, it is recommended that  notebooks use

     import matplotlib.pyplot as plt
     import numpy as np

Let's do that -- I noticed @reachtarunhere used `%pylab` in the very nice `rl.ipynb`, and there may be others. One big problem with `%pylab` is that it imports some `numpy` functions that override existing functions, for example,`numpy.core.fromnumeric.any`, which is not compatible with the builtin `any`.

**Comment by reachtarunhere** [comment]
I was not aware of this. I will make the required changes and send a PR.
