### ISSUE TITLE
Adding doctests to travis

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-python#195]
@reachtarunhere and others: I wanted to run the doctests, so I added

     - python -m doctest -v *.py

to travis, but I broke the build because travis can't `import IPython` in `ipyviews.py`. Any suggestions on the cleanest way to fix this?

**Comment by norvig** [comment]
I fixed it by putting a `try:` / 'except ImportError` in `ipyviews.py`.

**Comment by SnShine** [comment]
@norvig, #196 fixes this. We just need to install Jupyter on travis.
