### ISSUE TITLE
no noqa?

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-python#201]
In a previous version of this code base, utils.py had support for multiple versions of Python, and did things like define the set type for old versions of Python that didn't have it. So it made sense to do "from utils import *" because you'd be importing different things for different versions of Python.

But now we're only supporting Python 3.4+, there is no such confusion, and I think it would be cleaner to replace all the "import *" with specific "from module import x, y, z" statements. That makes it easier for a reader/user to determine where a name comes from -- they need only search the current file. 

Doing this replacement will also allow us to eliminate the #noqa comments.

**Comment by reachtarunhere** [comment]
I am working on this.

**Comment by norvig** [comment]
Thanks!
