### ISSUE TITLE
Should core code require IPython?

### ISSUE THREAD

**Issue by darius** [aimacode/aima-python#226]
When I don't have IPython installed, the tests fail because `games` imports `canvas` which imports from `IPython`. The dependency should be either documented or turned into a lazy import so that it fails only when you try to run some code that actually uses `canvas`. The latter seems more reasonable right now given that it looks like there's just this one instance of the pattern.

**Comment by norvig** [comment]
I agree -- we shouldn't fail in that case.

**Comment by Chipe1** [comment]
How about moving all the canvas code to canvas.py
It used to be in the notebook itself, but then I moved it to games.py after Jupyter was added to the build. Is it possible to have the code in the notebook itself and hide it(but still execute it)?

**Comment by norvig** [comment]
Moving it to notebook will work. The notebooks really should have a way to collapse a cell so that by default it is not visible, but so far there is no such mechanism built in. Possibly we could do it with some fancy CSS.

**Comment by SnShine** [comment]
Hmm... We will be implementing visualisations for searching algorithms shortly and we will use Python in search.py also. It would be better if we document IPython as a dependency.
And @darius, what's your opinion on having a wiki page for aima-python? Our README is very long and I think it might be useful if we can move some tables to wiki pages.

**Comment by reachtarunhere** [comment]
I feel that the idea to document IPy as a dependency is a good one. This is because we might want to have tests for canvas.py or ipyviews.py at a later stage.

**Comment by darius** [comment]
@SnShine I'd at least wait till the tables are full (or nearly) before moving them -- it seems encouraging for a potential contributor to see the open parts right away, and gives others a quick idea of how useful they might find the project. When we can summarize the tables as "all the pseudocode in the book" there'll be a stronger case for moving them.
