### ISSUE TITLE
README file links broken

### ISSUE THREAD

**Issue by radlyeel** [aimacode/aima-python#231]
In the top level README.md, the file links in table "Index of Code" are all broken, having a path prefix of ../master/, when no prefix seems preferred.  Suggested corrected version is attached.
[README.zip](https://github.com/aimacode/aima-python/files/253759/README.zip)

**Comment by SnShine** [comment]
Hey, are you talking about the README.md in master branch? They aren't broken and working fine with me. Would you like to check again?

**Comment by radlyeel** [comment]
I think it must be my own (mis)understanding of the directory structure.  When I click the files from inside a browser looking at the github repository, everything is fine.  But when I cloned the repository, brought up the README with my markdown editor, and then clicked the link there, I got a bad link error.  So I guess the only problem is mine.  Thanks for the quick response.
