### ISSUE TITLE
How should algorithm READMEs be completed and organised?

### ISSUE THREAD

**Issue by thundergolfer** [aimacode/aima-python#234]
It says in your contribution readme that you would like to have readme files added for individual algorithms. I would be happy to complete some of these when I have time, but I am afraid that there is not enough information on what should be in them, and where they should be placed in the repo.

Could you please add some guidelines, or point to good practice in another repo to work from?

**Comment by reachtarunhere** [comment]
As of now work is in progress on providing how to use guides and example code as a part of Jupyter Notebooks. You can give few of those a look to get an idea. Currently, the work in this regard is in its infancy and we are working to make it as complete as possible.

**Comment by go-bears** [comment]
I'd like to help with the how- to-use guides in the notebooks. I submitted a pull request that fixed some typos, spacing, and clarity issues in the search.ipynb file. Would it be ok to keep on working on adding examples and explanations?

**Comment by SnShine** [comment]
Yeah, @go-bears, that would be cool. You can refer some of the (partially) completed notebooks how to proceed writing the notebooks.
