### ISSUE TITLE
[Binder] Do we need to update binder whenever we update our notebooks?

### ISSUE THREAD

**Issue by SnShine** [aimacode/aima-python#238]
I could't see latest updates in our notebooks (index.ipynb) when pressed launch binder button. Do we need to update our repo every time we modify notebooks - http://mybinder.org? Or would binder take some time to reflect those changes?

**Comment by reachtarunhere** [comment]
You need to go to mybinder.org and build again. Please make sure you use the requirements.txt option. Unfortunately their system works in this manner at present though they have promised to fix this in later versions.
