### ISSUE TITLE
Mistake in depth_limited_search in Search.py on aima3python2 branch

### ISSUE THREAD

**Issue by matthewh806** [aimacode/aima-python#239]
I was wondering if fixes / pull requests are still accepted for the legacy branch?

I was browsing the Search.py file and noticed that depth_limited_search has a mistake. This issue has been addressed on the [master](https://github.com/aimacode/aima-python/commit/464ca5df146316f1f0ceb52a4fa186cdfc222567) branch. 

The same fix could be applied on the legacy branch if it is still maintained.

**Comment by reachtarunhere** [comment]
The legacy repo is not actively maintained but any contributions that improve code in it are always welcome :) Though it is not a mistake in the implementation itself. I was actually wrong in th commit you have linked. There was an issue with the test case. The changes I have made are only to reflect the new pseudocode in the 3rd Edition.

**Comment by matthewh806** [comment]
Ah right okay. I'm looking at the new global edition of the book which also uses the new pseudocode.

Sorry for any confusion!
