### ISSUE TITLE
ac3 in csp.py

### ISSUE THREAD

**Issue by onursurme** [aimacode/aima-python#256]
at line 171 in csp.py,  in the function AC3, it is written as : 
`if Xk != Xi:`

there is no need to exclude Xi because Xi already can't be a neighbour to itself.
but I guess it should be 
`if Xk != Xj:`
because Xi is already revised with Xj, so there is no need to add Xi, Xj to the queue again.

we can also see this in the book at Figure6.3 as :
`for each Xk in Xi.NEIGHBORS - {Xj} do`
here again, Xj is excluded.

**Comment by darius** [comment]
You appear to be right -- thank you!

We're also missing a test that would provoke this bug. Would you like to make a pull request with a new test case, or should I?

**Comment by onursurme** [comment]
I'll try to create a test. I'll inform you about the result.

Sent from Yahoo Mail on Android 
 
  On Fri, 2 Sep, 2016 at 6:14, Darius Bacon<notifications@github.com> wrote:   
You appear to be right -- thank you!

We're also missing a test that would provoke this bug. Would you like to make a pull request with a new test case, or should I?

**Comment by onursurme** [comment]
Here is a test case which I think reveals the bug :
```
from csp import *

def t1f(A,a,B,b):
    return int(a)>int(b)

test1=CSP(["a","b"],{"a":["2","4"],"b":["3","5"]},{"a":"b","b":"a"},t1f)
AC3(test1)
print(test1.infer_assignment())
```
a must be bigger than b, so b can't be 5, and a must be 4.
when I run this test with the wrong version of AC3 (if Xk != Xi: version), the test says b=5, which is wrong.
but when I run the test with the right version of AC3 (if Xk != Xj: version), the test says a=4, which is true.
