### ISSUE TITLE
verifying if am not misusing search module

### ISSUE THREAD

**Issue by cppchedy** [aimacode/aima-python#283]
Hi,
first, I want to thank you for this awesome library/work and to encourage you to continue developing and maintaining AIMA-Python.
<hr>

I am using AIMA-python in my homework/project of AI and it's my first time with your library.
I was reviewing one of the examples in the notebooks after that I completed implementing my solution and it made me suspicious. that's why I am here to verify  a few points/assumptions.

I inherited from Problem class  and reimplemented the is_goal() method, the result() method and the actions() method.
In the actions() method:

- is it valid to return empty actions?

 I am asked to use astar algorithm:
- is it sufficient to implement only H in my sub-class?

thx.

<b>Note :</b>sorry to post here I didn't find any other way to contact you.

**Comment by Chipe1** [comment]
By empty action if you mean no action i.e. empty list, then it is valid. If no action is possible and goal cannot be reached the function returns None. It is sufficient to implement h(), define the 'problem' and pass problem,h to astar_search.

**Comment by cppchedy** [comment]
thanks.
good, so I guess My implementation is correct. I will share it(I.A.) when I am done in a notebook.
