### ISSUE TITLE
Improve Test Coverage for learning.py

### ISSUE THREAD

**Issue by reachtarunhere** [aimacode/aima-python#286]
The learning.py module has a lot of code but only a few tests defined in the corresponding test file. You can help by adding tests for some of the functions and methods.

**Comment by AnshulBasia** [comment]
Can I start writing tests for Dataset class ?

**Comment by MrDupin** [comment]
Added tests for the following algorithms:

- PluralityLearner
- NaiveBayesLearner
- NearestNeighborLearner

I'm working on tests for other learners.

**Comment by AmeetR** [comment]
I'd like to help with this issue. Which tests still need implementing that no one else is working on?
