### ISSUE TITLE
Improve Test Coverage for csp.py

### ISSUE THREAD

**Issue by reachtarunhere** [aimacode/aima-python#287]
The csp.py module has a lot of code but only a few tests defined in the corresponding test file. You can help by adding tests for some of the functions and methods.

**Comment by kushagraagrawal** [comment]
is this issue still open?

**Comment by jayantsaraf** [comment]
can i still contribute to this issue?

**Comment by DeadlyHollows** [comment]
Can I still contribute to this issue?
