### ISSUE TITLE
Modern String Formatting in Code

### ISSUE THREAD

**Issue by reachtarunhere** [aimacode/aima-python#288]
It would be nice to move % string formatting to .format() throughout the codebase as per [PEP 3101](https://www.python.org/dev/peps/pep-3101/)

Refer to [this link](https://pyformat.info) for examples.

**Comment by deepanshugarg257** [comment]
@reachtarunhere I was started working on this issue and changed learning.py. But, learning.py was failing the test before I made any changes. 
Could you please look into it?

**Comment by sam0410** [comment]
Hi @reachtarunhere !
In what all files do we need to enhance the code?
Thanks!

**Comment by sampadsaha5** [comment]
Hi @deepanshugarg257 and @sam0410, I encourage your interest over this issue. I have already fixed it. You can have a look at #292. Feel free to rectify me over that PR.
