### ISSUE TITLE
Bug in DecisionTreeLearner in learning.py

### ISSUE THREAD

**Issue by theSparta** [aimacode/aima-python#295]
In the `count` function in the class `DecisionTreeLearner`, on running the learner on the `restaurant` dataset, gives the following error:

    return count(e[attr] == val for e in examples)
    TypeError: count() missing 2 required positional arguments: 'val' and 'examples'

79d7d5753b57317ecb5a9e94c981975d22324d49 in #293 fixes this.

**Comment by theSparta** [comment]
@norvig @vidursatija 
#301 is incorrect, on running the DecisionTreeLearner on the restaurant dataset gives the following error:

     return len(e[attr] == val for e in examples)
     TypeError: object of type 'generator' has no len()

The commit 79d7d57 in #293 fixes this correctly and this was also the cause of conflict in #293.

**Comment by MrDupin** [comment]
I can confirm that Sparta's fix throws no error, while #301 throws the TypeError mentioned above.

Both <i>count</i> (the previous method) and <i>len</i> (the current one) throw errors.
