### ISSUE TITLE
Issues on learning.py + Its Notebook

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#308]
I started working a bit on learning.py, and I have noticed some issues I need some directions on.

a) All the Learners require a DataSet object as input. Unfortunately, even though for some learners (like the kNN learner) it works intuitively, for others (like the NeuralNetLearner) it requires some actual pre-processing of the dataset. If I'm given the green light, I will implement these additional functions so that all the learners are ran the same way. Or, we could write some documentation on how to pre-process the datasets for each algorithm, as now it is difficult to gauge what an implementation requires.

An example to understand what I'm talking about:

`zoo = DataSet(name="zoo")`
`NaiveBayesLearner(zoo) # This works`
`NeuralNetLearner(zoo) # This doesn't work`

b) The Jupyter Notebook for the file is mainly focused on this one dataset, with some side-tracking for libraries like NumPy and Scikit-learn. Not much is written about the actual implementation of the algorithms on AIMA. I would like to help on this Notebook, but I am not sure of the direction we want this taken. I have the following suggestions:

1) Don't work with the MNIST dataset (or at least don't spend as much space on it as we currently do). I believe a simpler dataset, like Fisher's Iris, would work better in showcasing the algorithms.

2) Remove information about external libraries.

3) Write some information about the algorithms, showcase the code and write a small tutorial on their usage.

I have made a small sample notebook on #318. I plan on writing more on the same style, if approved.

---

What do you guys think about that? I'm happy to discuss this and change things up. I just want to make sure I know where we want to take this before I jump in.

PS: Sorry for the long post.

**Comment by norvig** [comment]
I agree that all learning algorithms should take the same data object as input. This can be `DataSet`, or possibly we want to adopt some existing framework; probably pandas.DataFrame. I'm not sure whether to go for pandas or not. We can show some techniques for DataSet-to-DataSet transformations, and how some algorithms perform better once these transformations have been applied.

I want to keep the MNIST example, but I agree that another, simpler example would also be useful.

I agree that the external libraries, if used, should be documented elsewhere.

Your (3) tutorial idea is exactly the right thing.

**Comment by MrDupin** [comment]
> We can show some techniques for DataSet-to-DataSet transformations, and how some algorithms perform better once these transformations have been applied.

I have written a couple of such functions for my own testing. One converts class names to numbers and the other removes a given column from the dataset. I would like to share/contribute them, but I don't know how.

Can I add them as functions to the DataSet class? This would be very helpful, I think. Or, I could add them to utils.py? Or, I could simply showcase them in the notebook, but I believe it would be best if we had them implemented.

**Comment by MrDupin** [comment]
I added #333 that implements a new function under the DataSet class to convert class names to numbers. More information on the PR.
