### ISSUE TITLE
Image Not Showing

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#316]
In [games.ipynb](https://github.com/aimacode/aima-python/blob/master/games.ipynb), the image for Game52 is not showing. The image that should be there is [this](https://github.com/aimacode/aima-python/blob/master/images/fig_5_2.svg).

Does that happen because fig_5_2 is an svg instead of png?

**Comment by Chipe1** [comment]
The issue is only when we use github to view the notebook. Using http://nbviewer.jupyter.org or any other notebook viewer renders the image properly.

**Comment by MrDupin** [comment]
Ah, good to know.

Isn't that still an issue though? I assume a lot of people interact with the repo online, straight from GitHub.

**Comment by Chipe1** [comment]
I don't think github has a proper notebook viewer. It only supports viewing not interaction or running the python code.

**Comment by MrDupin** [comment]
Fixed by #353.
