### ISSUE TITLE
Algorithms already implemented

### ISSUE THREAD

**Issue by hackrush01** [aimacode/aima-python#331]
I was recently looking at the pseudo-code of Spare-Tire Problem and was thinking of implementing it, but when I opened the `planning.py` file, it looked like the problem was already implemented(see [here](https://github.com/aimacode/aima-python/blob/master/planning.py#L141)). So does the README.md need updation? Also can you point me to the algorithms which are not yet implemented, as I am trying for GSoC this year.

**Comment by kaivalyar** [comment]
@hackrush01 I think so. I have found some other discrepancies too with the README, but I wouldn't jump to conclusions - maybe we're both missing something.

**Comment by MrDupin** [comment]
Hi @kaivalyar, could you please point out the inconsistencies in the README? It would help a lot.

**Comment by hackrush01** [comment]
https://github.com/aimacode/aima-python/pull/253
and
https://github.com/aimacode/aima-python/pull/232
seem to suggest that some algorithms are already implemented.

**Comment by kaivalyar** [comment]
@hackrush01 yeah maybe we should update the README to reflect these changes.

@MrDupin I was glancing through agents.py functions that were mentioned as complete in the README, but I couldn't locate them in agents.py. I've found **SimpleReflexAgent** and **TableDrivenAgent**, but haven't given it more than a cursory glance so there could be more.

It is worth noting here that factory methods for both these still exist, just the final implementation as in the README/pseudocode is missing. I'll be sending a PR soon with these issues (#330) fixed, hopefully.

**Comment by kaivalyar** [comment]
@MrDupin:
10.1 air cargo problem
10.2 spare tire problem
10.3 three block tower
10.7 graph plan

seem to all be implemented too.

**Comment by MrDupin** [comment]
Thanks @kaivalyar. If you want, you can make a PR updating the README and wait for @norvig to weigh in.

**Comment by kaivalyar** [comment]
I am waiting to identify all such instances before doing that, @MrDupin - or do you think it's better to make multiple edits, as and when I find them?

**Comment by MrDupin** [comment]
I think it would be best if you wait till you collect most of them.
