### ISSUE TITLE
"epoches" vs "epochs"

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#335]
In learning.py, I noticed that in every learners the word "epoches" is used. In the LinearLearner though, the word used is "epochs".

In all the literature I've read so far, the word is not spelled "epoches" but "epochs". This is true for English in general.

What is the course of action? Do we want "epoches" or "epochs"?

**Comment by Chipe1** [comment]
Probably a spelling mitsake. Even the book uses epochs so I think that should be used

**Comment by MrDupin** [comment]
Fixing this in #336.

**Comment by norvig** [comment]
thanks.
