### ISSUE TITLE
gsoc2017: Implementation of Chapter 19 - Knowledge in learning

### ISSUE THREAD

**Issue by Ridhwanluthra** [aimacode/aima-python#341]
I have thoroughly read the material in the chapter.
Working on building the implementation.
A few questions:
1 - Do you recommend adding the implementation to the learning module or creating a new one?
2 - I would request for your inputs on the representation of the hypothesis? (how about a simple circular or rectangular decision boundary, like in the book example. it would be pretty straightforward to implement and would help explain the concepts in an easy manner.)
3 - Do you have a dataset in mind which would be ideal for these problems?

**Comment by jaydeepingle** [comment]
@Ridhwanluthra 
Hey have you talked with any of the mentors regarding this. I am also interested in implementing chapter 19 algorithms.
