### ISSUE TITLE
Simple-Problem-Solving-Agent

### ISSUE THREAD

**Issue by kaivalyar** [aimacode/aima-python#367]
Figure 3.1 contains pseudocode for a "SIMPLE-PROBELM-SOLVING-AGENT". Similar to some names in agents.py (#330), the README.md states this as completed in `search.py` as `SimpleProblemSolvingAgent,` however, the code is actually implemented within the `__call__` method of the `SimpleProblemSolvingAgentProgram` class. I have found such a pattern in multiple places now, so I am unsure whether this is just a minor error, or a deliberate design feature.

**Comment by reachtarunhere** [comment]
It is deliberate. If you notice the pseudocode of SIMPLE-PROBLEM-SOLVING-AGENT the `seq` variable needs to be **persistent**. Doing that the functional way (as in agents.py) would have required us to have it as some sort of global. The `__call__` trick helps us avoid this while making SIMPLE-PROBLEM-SOLVING-AGENT behave similarly to a function.

**Comment by kaivalyar** [comment]
Oh wow - that is a very neat solution! Thanks for clarifying. I'll try to use this approach when writing codes for other sections too.

**Comment by darius** [comment]
Since we use Python 3, which has the `nonlocal` declaration, a nested function can implement this kind of state with no trouble (and in my opinion less fuss). A better reason to use a class here is to leave hooks for overrides, like `update_state` and `formulate_goal`.

**Comment by reachtarunhere** [comment]
@darius You are right. Not really used to all new Python 3 features so ended up not thinking about it. While we could pass update_state and formulate_goal as args too I like the current solution more with all functions tightly coupled.

**Comment by darius** [comment]
I agree, the template-method pattern seems like a good fit.
