### ISSUE TITLE
raise NotImplementedError : do these have to be coded. ( shows done in README.md)

### ISSUE THREAD

**Issue by sofmonk** [aimacode/aima-python#371]
Sir,  figure 9.3 FOL-FC-Ask in logic.py shows,

`
def fol_fc_ask(KB, alpha):
    raise NotImplementedError
`

but in README.md it says it is done,
so it has to be coded ?

same for class KB functions:
`
class KB:

    def __init__(self, sentence=None):
        raise NotImplementedError

    def tell(self, sentence):
        "Add the sentence to the KB."
        raise NotImplementedError

    def ask(self, query):
        """Return a substitution that makes the query true, or, failing that, return False."""
        return first(self.ask_generator(query), default=False)

    def ask_generator(self, query):
        "Yield all the substitutions that make query true."
        raise NotImplementedError

    def retract(self, sentence):
        "Remove sentence from the KB."
        raise NotImplementedError`

all the functions with "raise NotImplementedError" have to be implemented?

**Comment by kaivalyar** [comment]
Hi,

I am not sure about this particular case, but I can safely say that **ALL** such functions don't have to be coded. Often, if a class is abstract, you want programmers to extend it and override a function - in which case you define it, but don't implement it.

That being said, I don't know about this particular case for sure. Maybe somebody else can weigh in on this?

**Comment by Chipe1** [comment]
KB is complete. It just acts like a skeleton class which other classes like FOLkb inherit from. 
fol_fc_ask() is not yet implemented. Would be helpful if you changed the README or implemented it.
