### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#375]
Something must have broken the build. Even trivial changes like in #343 (which simply adds text on a Notebook) fail.

I believe #373 fixes this.

**Comment by sofmonk** [comment]
yes, test_text.py and test_agents.py, it shows flake8 errors, fixed that in PR #373 , will have to wait for merge.

**Comment by kaivalyar** [comment]
Yes, as mentioned in #304, now onwards, any tests that don't match flake8 specs will break the build - and one of my PRs that had such tests is breaking the build.

**Comment by Chipe1** [comment]
I have removed the test in #386 . That should the problem

**Comment by MrDupin** [comment]
This is now fixed. Closing.
