### ISSUE TITLE
intersection query in relevant_pages (nlp.py) 

### ISSUE THREAD

**Issue by bionascu** [aimacode/aima-python#392]
relevant_pages in the nlp.py module currently returns pages that contain the query in its entirety, but according to the textbook (p.872) it should do it "by intersecting hit lists of query words". 

My understanding is that for `query = "green apples"` and pages `p1 = "oranges and bananas"`, `p2 = "red and green apples"`, and `p3 = "plums and apples"` relevant_pages(query) should return p2 and p3, not just p2 as it currently does.

I can make this quick fix and change the corresponding test if someone confirms that it is indeed an intersection that we want.

**Comment by RojerGS** [comment]
"Intersecting hit lists of query words"

Feels like the query for the word "green" gives Query1 = {p2} and the query for the word "apples" gives Query2 = {p2, p3}. Intersecting Query1 with Query2 yields {p2}, the returned, expected result. Am I missing something?

**Comment by bionascu** [comment]
I'm writing intersection and the whole time I'm thinking union!! My bad.

**Comment by RojerGS** [comment]
And as of now, it only returns p2? If so, that looks wrong.

**Comment by bionascu** [comment]
Yes, as of now it only returns p2. But hopefully not for much longer :)
