### ISSUE TITLE
Skip test if data directory is not present

### ISSUE THREAD

**Issue by OrkoHunter** [aimacode/aima-python#40]
> What steps will reproduce the problem?

Running test on a newly cloned repository.

> What is the expected output? What do you see instead?

We expect the tests to fail only if the code is broken. Tests fail with little less informative error.

> What version of the product are you using? On what operating system?

GitHub master, Linux Mint 17.3

> Please provide any additional information below.

A warning should be raised to get the `data` repository for the tests to complete. If the directory is not present, it would be good to skip the test with an informative message.

I'd like to work on it, if the issue is accepted.

**Comment by chiragvartak** [comment]
Just putting the `data` directory should fix this right? Download it from [here](https://code.google.com/archive/p/aima-data/source/default/source), unzip it and put this unzipped folder alongside your `aima-python` folder. Make sure to rename this unzipped folder to `data`.  

Also, I didn't understand what you mean by 'skip the tests' when you are explicitly asking to run them. If you don't want the tests to run, don't run them.
