### ISSUE TITLE
Loop Syntax

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#400]
I have noticed that in the book loops are usually defined like this:

<pre>
for i=1 to n:
    do something with Xi
</pre>

but in the implementation we have something like this:

<pre>
for Xi in X:
    do something with Xi
</pre>

Should this be changed? On one hand this is trivial, but on the other hand we should be keeping the code as close to the pseudocode as possible.

**Comment by RojerGS** [comment]
(do you mean "`do something with Xi`" instead of "`X`"?)

And how is X usually defined?
A regular python loop iterating over the first `n` integers is usually seen as
`for i in range(1, n+1):`

which, unfortunately, doesn't look that similar to
`for i=1 to n:`

However it becomes ugly if we do something like
```python
X = list(range(1, n+1))
for i in X:
    do something with i
```

**Comment by reachtarunhere** [comment]
In my (strong) opinion this should not change. Python by default uses the for-each type of loop syntax and moving to an indexed based system would make it difficult to read (and very unpythonic). 

The current code is not too difficult to read for someone following book but the index based syntax would irritate someone who has been using Python for some time and might instill bad habits into people who are new to the language.

**Comment by RojerGS** [comment]
Oh I understand the problem now. The point is, if we want to iterate over the elements of X, then we could have
```python
for Xi in X:
    #do something with Xi

for i in range(n):
    Xi = X[i]
    #do something with Xi

for i in range(1, n+1):
    Xi = X[i-1]
    #do something with Xi
```

The first one is the most pythonic but doesn't mimic the fact that the pseudocode is traversing the indexes, and not the elements of X directly. The last one is the ugliest one in my opinion, but the second one seems pretty decent.

**Comment by MrDupin** [comment]
@RojerGS, yes, that is what I meant to say. The three examples you posted capture my issue perfectly.

Personally I prefer the first one, but the second and third ones seem closer to the book.

**Comment by RojerGS** [comment]
From my (limited) experience with explaining loops to my fellow colleagues, the first loop is "harder" to explain while the second one is clearer for them: _just go through all valid indexes and grab the corresponding item, calling it Xi_. Unexperienced programmers can't quite grasp the fact that

```python
for Xi in X:
```
is already taking all values in X in order Maybe the second type of loop would be desirable? The one with `i in range(n)`

**Comment by reachtarunhere** [comment]
@RojerGS  It is the other way round if your collegues use python as the main language. I expect this to be the case with most people coming to aima-**python**

**Comment by kaivalyar** [comment]
@RojerGS is it possible that you're talking about people who learnt programming using languages other than python? The for each syntax is the more intuitive one otherwise, I think.

**Comment by MrDupin** [comment]
Most people who use a language other than Python will find the `range` method more intuitive. People who have used Python for some time will prefer the other method. But most people checking aima-python are (I assume) people who have actually used the language. So it's not a question of "which is more intuitive to users", but of "which is closer to the book and does it matter".

Another issue that should be considered is that of partial iteration. In the book we can find code like this:

<pre>
for i=2 to n:
    do something with Xi
</pre>

Which can be done with the range function like this: `for i in range(2,n)`, but for the other method it's `for x in X[1:]`.

So, `range` is more consistent while for the other way we must change it up a bit in special cases.

I prefer the `for x in X`, since it's more Pythonic, but ultimately it is up to @norvig.

**Comment by kaivalyar** [comment]
@MrDupin Yes, I think we can safely assume that the users of aima-python are comfortable using python, especially because there are other repositories for other languages.

**Comment by reachtarunhere** [comment]
@MrDupin `range(2, n)` is not the same as the loop you mentioned because:
Arrays in the book are 1-indexed while in Python and most programming languages they are 0-indexed. So for an array/list of size n where you want to skip the first element, we would use `range(1, n)`

I don't think we can do away with the 1, 2 issue here. Further, I feel it is not a big problem given rules/guidelines (including the rule for sticking to pseudocode) are to help us make sure that we don't do convoluted things that make the reader think too much. Some distance from the pseudocode as long as it is obvious is not a big issue.
