### ISSUE TITLE
Chapter 11 algorithm implementations

### ISSUE THREAD

**Issue by kaivalyar** [aimacode/aima-python#423]
Hierarchical Search and Angelic Search need to be implemented.

This would first require representing chapter 11 HLA plans in the code (done in #422). Once this is merged, I will start working on the other algorithms from chapter 11 (unless someone else has finished them already, in which case please let me know).

**Comment by DeadlyHollows** [comment]
Can I also contribute?

**Comment by kaivalyar** [comment]
@DeadlyHollows sure! I am unsure whether you meant contribute to aimacode generally, or to chapter 11 specifically, so I'll just assume both. You can find unimplemented algorithms on the README. (If you're interested in GSoC, then maybe the ideas page or the gitter channel is a good place to start.) As for chapter 11, I have already moved beyond #422, and finished most of the other pseudocodes from the book. I am now working on the jupyter notebook - will send a PR soon.
