### ISSUE TITLE
requirements.txt  incomplete

### ISSUE THREAD

**Issue by TheCDC** [aimacode/aima-python#431]
Hi! I'm a student hoping to work on this project for GSoC 2017.

Following the readme and installing only the `pytest` module and executing the `pytest` command fails when `IPython` can't be found.

The issue seems to be missing dependencies in `requirements.txt`. Instantiating a new env and installing everything in `requirements.txt` with the following commands does not set up the minimum environment to run tests.
```
virtualenv env -p python3
pip install -r requirements.txt
```

Notable omissions:
```
pytest
jupyter
nose
pyqt5
requests
```
Inserting those dependencies into `requirements.txt` and installing as normal runs the tests successfully.

**Comment by sofmonk** [comment]
You did follow all the steps?

The minimal requirement for running the testsuite is py.test. You can install it with::
`pip install pytest`

Clone this repository::
`git clone https://github.com/aimacode/aima-python.git`

Fetch the aima-data submodule::
```
cd aima-python
git submodule init
git submodule update
```

**Then** you can run the testsuite with::
`py.test`

**Comment by TheCDC** [comment]
Indeed I did I was able to get the tests running by adding those dependencies. I'm still new to this and don't want to be rude but if this project requires jupyter, nose, pyqt5, and requests shouldn't those be in the `requirements.txt`?

**Comment by MrDupin** [comment]
I could be wrong, but I think `requirements.txt` is there because [Binder](http://mybinder.org/) needs it.

**Comment by TheCDC** [comment]
Would it be a good idea to include all the dependencies in requirements so newcomers can do the normal process of `pip install -r requirements.txt` to get everything installed?

**Comment by Chipe1** [comment]
I am able to run the pytest without nose. I'm not sure why we require pyqt. Adding it to requirements.txt won't help as it installed by a distribution package manager not pip.

**Comment by TheCDC** [comment]
Interesting. When I'm in the env and I run `py.test` without nose most of the errors are failures to import nose.

**Comment by Chipe1** [comment]
@TheCDC can you say what error message are you getting and which file is causing the error. The only reference to nose I could find is nosetests.xml in gitignore file

**Comment by TheCDC** [comment]
Woops, it appears that I am mistaken about nose. Running py.test runs the test in all installed modules including networkx which requires nose to run its tests.

**Comment by darius** [comment]
This particular error with the tests needing IPython is fixed now (see #226). I don't know whether the other requirements mentioned need to be added, because I'm not exactly sure what requirements.txt is used for. (Just explaining why I'm not closing this issue along with #226.)

**Comment by darius** [comment]
I guess the question is whether it's meant to list the minimal requirements to do anything, or everything you might want.

**Comment by TheCDC** [comment]
I'm of the opinion that it should include everything but it definitely is ambiguous as to what it's really for. Should I close the issue, then? Or is there something else to do with the issue?

**Comment by reachtarunhere** [comment]
Sorry for replying so late. I have been really busy. @MrDupin  is right the requirements.txt is for Binder.
