### ISSUE TITLE
Normalize for HITS algorithm

### ISSUE THREAD

**Issue by Chipe1** [aimacode/aima-python#442]
In the pseudocode for HITS, normalize is defined to divide each page’s score by the sum of the squares of all pages’ scores. The standard definition or normaliztion divides a value by the norm of the vector that contains it. In our case shouldn't we divide by square root of sum of squares as opposed to just the sum of squares.
@norvig Is this an error in the book or am I wrong. I tried running HITS using the definition given in book and that lead to an infinite loop. The values started oscillating between two states, whereas changing the normalize() in #439 leads to convergence.

**Comment by norvig** [comment]
Yes, the scores should be normalized to the square root of the sum of the squares.
