### ISSUE TITLE
Movement Orientations?

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#449]
In `grid.py` there is a set of orientations, defined as follows:

`orientations = [(1, 0), (0, 1), (-1, 0), (0, -1)]`

I snooped around a bit, but I couldn't find what these mean. From my understanding they are showing where the current agent is looking in a 2D plane (Forward, Backward, Left, Right). I don't know though which is which. It would be nice to have this documented.

PS: I believe (0,1) is forward, (0,-1) back, (1,0) east and (-1,0) west, since that's how I've encountered it in literature. Not sure if this is the case here too though.

**Comment by RojerGS** [comment]
I am not familiar with the literature but let me just say that that is definitely what makes more sense, if you think of two-dimensional vectors in mathematics.

The vector (1,0) points east, the vector (0,1) points north/up, the vector (-1,0) points west and the vector (0,-1) points south/bottom.

**Comment by MrDupin** [comment]
The issue is that the code doesn't reflect that. Take for example the function `turn_left`. If we are facing north and turn left, we are now facing west, right? In the code that doesn't happen.

`turn_left((0,1))` returns (-1,0)

**Comment by MrDupin** [comment]
*The page jumped and I accidentally closed this. Sorry.*
