### ISSUE TITLE
Fixing links in ProjectHome.md and including its contents in Readme.md

### ISSUE THREAD

**Issue by chiragvartak** [aimacode/aima-python#46]
I suggest moving the page [ProjectHome.md](https://github.com/chiragvartak/aima-python/blob/wiki/ProjectHome.md), which contains the table of implemented and not implemented algorithms to the Wiki section (only the owner of the repo can do that currently; if that could be changed so as to allow other users to edit and create wikis?). The links in this page will have to be modified to point to corresponding files on Github rather than Google Code.

**Comment by reachtarunhere** [comment]
@chiragvartak  Can you elaborate on what you mean by moving the page? For now I have sent a pull request which deals with changing the links of the Index. Please let me know if you want to it to be somehow different.

**Comment by chiragvartak** [comment]
Well, I thought that moving the ProjectHome.md file to the Wiki section would be appropriate but after having a look at [aimacode/aima-java](https://github.com/aimacode/aima-java), including it's content in the Readme.md of the repo seems to be the way to go. I'll edit the title of this issue accordingly.  

But never mind, your edits are still valid. Now after fixing #45 and including your edits, the new Readme.md would be proper for Github, I believe.

**Comment by reachtarunhere** [comment]
Or possibly, we move the content including the Index and the Setup Guide as separate files and link them to the main readme to keep it short. (Like the aima-java implementation). Nevertheless, I think this is best left for the repo maintainers and owners to decide.

**Comment by norvig** [comment]
I moved the index into the main README. But I confess I don't understand how a wiki is supposed to be used. To me it feels a bit hidden -- a user has to discover that it exists in the "Branch:" oulldown, whereas the main readme is right there. Do we need a wiki branch at all?

**Comment by norvig** [comment]
I think the reason the wiki branch exists is because of tradition in code.google.com under subversion; I don't think we need to maintain that under github -- a random sampling of github projects do not have a wiki branch.

**Comment by chiragvartak** [comment]
I think a wiki branch is quite unnecessary. So, we create a wiki *page* with the necessary info and add a link to it in Readme.md. That way, the users do not have to 'discover' that page by themselves and also the Readme.me is not cluttered with too much information. Then we delete the wiki branch.

**Comment by norvig** [comment]
For now I put all the info on the Readme.md page and will ddelete the wiki branch; later we can sonsider breaking up the readme.md page.

**Comment by reachtarunhere** [comment]
I think it would be a good idea if we make the readme shorter. In my opinion it should mainly list stuff that is relevant for people who are going to use this code. This can include the index of implementations, structure, choice of programming and acknowledgements. For other details like how to contribute, style guide etc. we can have separate .md files that  have links in the main readme. We can do this in a clean manner by making a docs directory. This can be helpful as we add more details on how to use IPy notebooks etc.
