### ISSUE TITLE
Chapter 19: Knowledge in Learning

### ISSUE THREAD

**Issue by jaydeepingle** [aimacode/aima-python#461]
I would like to implement the below algorithms within this chapter
Current-Best-Learning
Version-Space-Learning
Minimal-Consistent-Determination
FOIL

**Comment by darius** [comment]
@jaydeepingle, that would be awesome. Opening an issue like this is a good idea, to make it less likely for two people to work on the same thing. So, I'd suggest picking one to start and posting that here.

**Comment by jaydeepingle** [comment]
@darius Sure Darius. As in sequence I would like to start with the first one and want to cover the whole chapter. I am also planning to look into the following
Chapter 11. Planning and Acting in the real world
1. Job-Shop-Problem-With-Resources
2. Hierarchical-Search
3. Angelic-Search
Chapter 25. Robotics
1. Monte-Carlo-Localization

Once I am done with 19 I will start with other chapters.

**Comment by darius** [comment]
Great!
