### ISSUE TITLE
section 6 csp.py

### ISSUE THREAD

**Issue by prasadwajekar** [aimacode/aima-python#468]
while executing file getting error : 
 File "./prog.py", line 3, in <module>
ImportError: No module named 'utils'

**Comment by Chipe1** [comment]
Could you paste the contents of prog.py

**Comment by darius** [comment]
A little documentation in the README on how to use these Python modules, for people not experienced with Python, would be helpful. Similarly, the instructions for the notebooks are in notebooks! If you've never run Jupyter this seems like a bit of a barrier to entry.

**Comment by norvig** [comment]
I updated README.md. Thanks for the suggestion.
