### ISSUE TITLE
logic.ipynb "Appendix: The Implementation of expr" equivalency claims incorrect

### ISSUE THREAD

**Issue by ltfschoen** [aimacode/aima-python#472]
In section [Appendix: The Implementation of expr](https://github.com/ltfschoen/aima-python/blob/master/logic.ipynb) of logic.ipynb it states equivalencies, however when I check if it returns True when I compare the claimed equivalencies with my Python 3.6.0 interpreter, they actually return False.

```python
from utils import *
from logic import *

# Returns False
expr('~(P & Q)  ==>  (~P | ~Q)') == symbols('P, Q')

# Returns False
expr('(P & Q)  ==>  (P | Q)') == symbols('P, Q')
```

**Comment by Chipe1** [comment]
It meant that `expr('~(P & Q)  ==>  (~P | ~Q)')` is equivalent to `~(P & Q)  |'==>'|  (~P | ~Q)` where `P` and `Q` are obtained by `P, Q = symbols('P, Q')`. You need to do this
```
from utils import *
from logic import *

P, Q = symbols('P, Q')

e1 = expr('~(P & Q)  ==>  (~P | ~Q)')
e2 = ~(P & Q)  |'==>'|  (~P | ~Q)
# returns true
e1 == e2
```
It claims equivalence between  `"A ==> B"`  and `A | '==>' | B`. Hope that clears your doubt.
