### ISSUE TITLE
logic.ipynb "Propositional Knowledge Bases: PropKB" ask_if_true function not exist

### ISSUE THREAD

**Issue by ltfschoen** [aimacode/aima-python#473]
In section [Propositional Knowledge Bases: PropKB](https://github.com/ltfschoen/aima-python/blob/master/logic.ipynb) of logic.ipynb it says the function `ask_if_true` may be used as an alternative, however this function does not exist in [logic.py](https://github.com/ltfschoen/aima-python/blob/master/logic.py)

**Comment by Chipe1** [comment]
It exists as a method for the PropKB class. It is not documented in the notebook but you can see it in [https://github.com/ltfschoen/aima-python/blob/master/logic.py](url) line 97
```
def ask_if_true(self, query):
    "Return True if the KB entails query, else return False."
    for _ in self.ask_generator(query):
        return True
return False
```
