### ISSUE TITLE
Modifying utils.py to work with Python 3+

### ISSUE THREAD

**Issue by gokul-uf** [aimacode/aima-python#48]
Code in utils.py have been implemented to fit the capabilities of python 2, as this repo is for code in python 3, we should modify this to reflect the same. I am working on this and will be sending a pull request for the same.

**Comment by gokul-uf** [comment]
Question: Should we keep backward compatibility as-is or should we move it to a separate branch/repo to keep the current repo clean?

**Comment by reachtarunhere** [comment]
Another important factor to consider is whether we need to do away/rename the custom implementations  for which there are native implementations in the newer version. I am specially curious about the cases where these custom implementations have different names then that of the native implementations in Python 3.

Example Case: DefaultDict (in utils.py), collections.defaultdict (in Python 3)t

**Comment by norvig** [comment]
reachtarunhere is right -- we should use the now-standard implementations and remove the legacy implementations and names. So, don't use DeafultDict, use collections.defaultdict throughout.

**Comment by ishaan1996** [comment]
utils.product and utils.argmin_list not working
------------------------------
utils.product([2,3,4])
NameError: name 'reduce' is not defined
------------------------------
a = ['one', 'two', 'three', 'six']
utils.argmin_list(a, len)
[]

**Comment by gokul-uf** [comment]
That is the final goal. There is another branch for transistioning python 2
code to python 3. Please check that out

S. Gokula Krishnan, Fourth-year Undergraduate student
Department of Computer Science
Birla Institute of Technology & Science, Pilani
Pilani Campus, Rajasthan, INDIA - 333031
