### ISSUE TITLE
Build Fail due to dependency

### ISSUE THREAD

**Issue by Chipe1** [aimacode/aima-python#498]
An undocumented dependency was introduced in #480 
I feel it is better to implement a simple function rather than adding a dependency for a library.
I'm not completely sure what fuzz.ratio() does exactly but after looking at the source code I think #497 can replace it for now.

**Comment by MrDupin** [comment]
*Days since last build fail: 0*

Well, we did have a one-day window of the build passing, so I can't complain. 😄

**Comment by MrDupin** [comment]
Now #501 fixes the issue and the algorithm.

**Comment by MrDupin** [comment]
The build now is passing.
