### ISSUE TITLE
Weird Issue with Weighted Sampler and Travis

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#502]
Hi guys. I have encountered an issue with the Travis checker that I for some reason can't replicate on my machine. I would like some help, if possible.

I recently rewrote the implementation of the genetic algorithm. The PR is #501. The code for the core algorithm was implemented (mostly, I did make some changes) by someone else before me. Here's the code (I blanked the arguments, since it's too long for Github comments):

```
def genetic_algorithm( ... ):
    """[Figure 4.8]"""
    for i in range(ngen):
        new_population = []
        for j in range(len(population)):
            fitnesses = map(fitness_fn, population)
            p1, p2 = weighted_sample_with_replacement(2, population, fitnesses)
            child = reproduce(p1, p2)
            if random.uniform(0, 1) < pmut:
                child = mutate(child, gene_pool)
            new_population.append(child)

        population = new_population

        if f_thres:
            fittest_individual = argmax(population, key=fitness_fn)
            if fitness_fn(fittest_individual) >= f_thres:
                return fittest_individual

    return argmax(population, key=fitness_fn)
```

I would like to bring your attention to the following lines:

`fitnesses = map(fitness_fn, population)`

and

`p1, p2 = weighted_sample_with_replacement(2, population, fitnesses)`

With these lines we pick randomly the most fit individuals. This line is called in each iteration. As it is right now there are no issues. Since though `population` doesn't change inside each generation, I thought it would be best to put the line outside the nested for loop, like this:

```
for i in range(ngen):
    fitnesses = map(fitness_fn, population)
    new_population = []
    for j in range(len(population)):
        p1, p2 = weighted_sample_with_replacement(2, population, fitnesses)
        ...
```

That way we save the time it takes to map fitnesses. When I ran the above in my machine, no errors are thrown. But when Travis checked, it actually threw the following error:

```
search.py:592: in genetic_algorithm

    p1, p2 = weighted_sample_with_replacement(2, population, fitnesses)

utils.py:202: in weighted_sample_with_replacement

    return [sample() for _ in range(n)]

utils.py:202: in <listcomp>

    return [sample() for _ in range(n)]

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   return lambda: seq[bisect.bisect(totals, random.uniform(0, totals[-1]))]

E   IndexError: list index out of range
```

I tried to replicate the error but I came up with nothing. Does anyone have any idea why that's happening? I find it weird that it fails when I put the line outside the nested loop and passes when it's inside, since it doesn't make much of a difference, right?

Any help is appreciated.

**Comment by MrDupin** [comment]
For the record, I am using a very old machine and it's quite probable some dependency is not up to date. I'm asking to make sure there is not something wrong with Travis.

**Comment by MrDupin** [comment]
Updated my system and I caught the error. Closing this, there is nothing wrong with Travis.

**Comment by darius** [comment]
Just noting a possible improvement on the code you posted: there's a function `utils.weighted_sampler` that could be used to hoist some of the work done by `weighted_sample_with_replacement`, to go along with the hoisting of calculating the fitnesses. After setting the fitnesses you'd also create the sampler; then inside the loop you'd call that sampler. This would speed `genetic_algorithm` up some, at the cost of making it a little harder to follow.

I don't remember why I wrote the code without any of the hoisting -- maybe it was meant to stay closer to the pseudocode? (Which don't have handy to look at just now.)

**Comment by MrDupin** [comment]
Thanks a lot for the suggestion, it sped things up a lot. Also, I believe it is even closer to the pseudocode now.

This is the new code:

```
def genetic_algorithm( ... ):
    """[Figure 4.8]"""
    for i in range(ngen):
        new_population = []
        fitnesses = map(fitness_fn, population)
        random_selection = weighted_sampler(population, fitnesses)
        for j in range(len(population)):
            x = random_selection()
            y = random_selection()
            child = reproduce(x, y)
            if random.uniform(0, 1) < pmut:
                child = mutate(child, gene_pool)
            new_population.append(child)

        population = new_population

        if f_thres:
            fittest_individual = argmax(population, key=fitness_fn)
            if fitness_fn(fittest_individual) >= f_thres:
                return fittest_individual

    return argmax(population, key=fitness_fn)
```

**Comment by darius** [comment]
Yep, that looks like just how it was meant to be used. I'm glad to hear it's effective.
