### ISSUE TITLE
aima-swift possibly?

### ISSUE THREAD

**Issue by Lxrd-AJ** [aimacode/aima-python#51]
Hi ,
I have been wanting to contribute to aimacode for a while now and wanted to apply through Google summer of code but I am on placement atm and thought the role might be more suited to someone else with more time.
From the readme i can see that you're looking to explore other languages such as C++/C# and a language with the readability of Python and type safety and speed of Java. I recently have been **exploring** Machine Learning using Swift and am porting the implementation from the Python programs from the book 

> Guide to Data Mining. http://guidetodatamining.com

 to swift , here is a link to the repository https://github.com/Lxrd-AJ/Floi that shows my recent progress. 
I have the aima book on my reading list but decided to go with a smaller book and work my way up due to the complexity of the book. 
I raised this issue because I was wondering if it is possible to consider a swift version of the code for this book. 

Many thanks.

**Comment by norvig** [comment]
It is a possibility, but I wouldn't put Swift in my top 10 list of languages. I think the priorities are to first finish Python and Java. Then, it might be nice to have one more language that combines the efficiency and type safety of Java with the terse expressiveness of Python. Swift is a reasonable choice for this, but it looks like Go and other languages fill a similar niche and are more popular. If Swift gains in popularity, we could reconsider. But if anyone comes up with a great Swift implementation, I would accept the pull request.
