### ISSUE TITLE
Value of gamma in MDP

### ISSUE THREAD

**Issue by Chipe1** [aimacode/aima-python#514]
Currently the code restricts the value of gamma to lie in the range [0, 1). Wouldn't it be better to the range set as (0, 1].
Setting a value of 0 results in ZeroDivisionError in value iteration algorithm.

**Comment by MrDupin** [comment]
I agree. Changing it to (0, 1] seems reasonable, unless the book states otherwise.

**Comment by norvig** [comment]
That makes sense.

**Comment by Chipe1** [comment]
Made the changes in #530
