### ISSUE TITLE
FIFIOQueue, inefficient, unpythonic.

### ISSUE THREAD

**Issue by theelous3** [aimacode/aima-python#515]
Hi there. I don't have the book that this codebase relates to, nor could I find a free version of it online. I came across this whilst helping someone and was just generally confused by the `FIFIOQueue` implementation.

I gather that the purpose of this codebase is not to write perfect pythonic code, so saying to throw the class away and just use a `deque` probably isn't helpful; however this brings up my fist issue / question. 

1. If the purpose of this code is to teach and / or give examples of how to implement data structures, the `FIFOQueue` being a direct wrapper of `collections.deque` doesn't accomplish that goal. If the code is going to be a wrapper around a `deque`, why not just subclass it?

2. Raising `Exception` in `pop` is unhelpful and redundant. `deque` already throws the correct exception. There are other general exceptions thrown in `extend` and `append`, which are unhelpful too.

3. Are the order of the args to __init__ intentional? They are backwards to deque, and python's style generally.

In light of this, I ran some timeit's on the current `FIFIOQueue` and a new `NewFiFoQueue` with a million calls to `.pop()`

```python
class FIFOQueue(Queue):
    def __init__(self, maxlen=None, items=[]):
        self.queue = collections.deque(items, maxlen)
    def pop(self):
        if len(self.queue) > 0:
            return self.queue.popleft()
        else :
            raise Exception('FIFOQueue is empty')

>>> timeit.timeit('[q.pop() for _ in range(20)]', setup='q = FIFOQueue(20000000, list(range(20000000)))', number=1000000, globals=globals())
6.41128579096403
```

```python
class NewFiFoQueue(collections.deque, Queue):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    def pop(self):
        return self.popleft()

>>> timeit.timeit('[q.pop() for _ in range(20)]', setup='q = NewFiFoQueue(list(range(20000000)), maxlen=20000000)', number=1000000, globals=globals())
3.675234421971254
```

Directly subclassing `deque` results in code that runs in ~57% of the time taken by the current class.
Deque is pure C, in Cpython, meaning layering python on top of it hampers performance significantly.

(Just actually using a deque by using `appendleft` and `pop` to implement FiFo is even faster still, running in 2 second flat.)

Anyway, I'm more curious than anything. Thanks for your time.

Mark.

**Comment by darius** [comment]
I think you're right that this class could be deleted. It was meant for Python 2.x where x is very small.

**Comment by theelous3** [comment]
Note that the other subclasses of `Queue` might be best replaced by something like the builtin `heapq`.

**Comment by norvig** [comment]
I think this is right -- FIFOQueue came from old Python 2 days. I also think that using Queue was a mistake, only done because of the attractive name. Python's Queue is really for multiprocessing, not for what we need it for,

**Comment by MrDupin** [comment]
I will take care of this shortly.

**Comment by MrDupin** [comment]
My PR is #544. I am not entirely sure this is what was asked though, I would like some feedback if possible.

**Comment by theelous3** [comment]
Yeah looks good as far as a subclass goes. Though why subclass at all and not just recommend deque?

**Comment by MrDupin** [comment]
I believe it is to adhere to the pseudocode, where "a FIFO Queue" is used.

**Comment by darius** [comment]
Python's collections module came along after the utils queue code was written. I think it's reasonable to replace `Queue` with `deque`.

**Comment by theelous3** [comment]
Well, all good then. My little inquiry is satisfied by pr https://github.com/aimacode/aima-python/pull/544
