### ISSUE TITLE
8 queen problem, please explain?

### ISSUE THREAD

**Issue by cool88** [aimacode/aima-python#517]
In the 8 queen problem, as a **complete-state formulation**, the book says, 

"The successors of a state are all possible states generated by moving a single queen to another square in the same column ( so the state has 8 x 7 = 56 successors)."

How is that 8 x 7 ? and what would be the successors of one of these 56 successors?  

I do not understand the meaning of "a single queen to another square". Do you mean you generate a successor by placing the queen one at a time in the rest of spaces in the same column? Thus generating 7 new states per queen - which will give 7 x 8 states. 

**While that makes sense as an idea, there is no explanation why this "parent"-successor relationship has been chosen, a proof that it is exhaustive when done recursively, or a comment on the repetition of such states.** 

When we talk about Depth First Search or BFS, we are clear that exploring neighbors continually will indeed exhaust all the states. I would like a similar justification for this exploration front in the 8 - Queen Problem.

Can someone please break it down for me?  I will appreciate your help.

**Comment by Chipe1** [comment]
An initial state has all Queens placed on the board. One queen in each column. The column of amy Queen remains fixed. A Queen changes its square within its column.
To generate a successor, we move one of the Queens to a new square (within its column). There are 8 Queens to choose from and 7 new positions available in its respective column. This makes the number of successors 7*8.
Hope this cleared things for you. We can see that any 1-Queen-per-column configuration can be obtained in atmost moves.
