### ISSUE TITLE
Does Backtracking Search fall in an infinite loop?

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#520]
I am running the notebook cells of csp, and sometimes backtracking search seems to get stuck in an infinite loop. Is that an issue with the notebook, the code, or just bad luck on my part?

I will take a look at this later myself, I'm bringing this up in case someone knows something about this.

**Comment by norvig** [comment]
What problem, and what command are you running? If there is an infinite loop, that's a bug. But for some problems the search space is very large, and it can take a long time.

**Comment by MrDupin** [comment]
```
solve_simple = copy.deepcopy(usa)
solve_parameters = copy.deepcopy(usa)

# below cell gets stuck
backtracking_search(solve_simple)
backtracking_search(solve_parameters, order_domain_values=lcv, select_unassigned_variable=mrv, inference=mac)
```


I am running the Backtracking section in the CSP Notebook from Input 14. Input 16 seemingly got stuck (you will notice that all input numbers are ascending by one, but after 14 came 16. That is because it got stuck and had to manually restart it). On the same problem, some times it gets stuck and other times it solves pretty much instantly.

Unfortunately we have not covered the algorithm yet in uni, so I can't be of immediate help here (I would have to study it first). From glancing at the code and pseudocode, I believe the algorithm is deterministic. That is why I find it odd that sometimes it gets stuck and sometimes it completes.

I don't remember encountering this issue on other IPython cells.

**Comment by norvig** [comment]
It is true that the algorithm is deterministic in that it doesn't call random. However, it does iterate over a dictionary, and the order of elements is non-deterministic between runs (it depends on the address of the elements that were added to the dictionary, and that can vary from run to run).

Still, if the algorithm doesn't terminate, that's a bug. It should keep track of previous paths and not revisit them, and so not get stuck in an infinite loop. In the worst case, I think it could take n! steps for n nodes (I'm not sure about that), but n is so small that that shouldn't be a problem, so there must be a bug somewhere.

**Comment by MrDupin** [comment]
I cannot replicate this behavior no matter how much I tried (over 100 tests with pytest). Unless someone can replicate it, I will close this issue shortly.
