### ISSUE TITLE
Pythonic way to represent infinity

### ISSUE THREAD

**Issue by gokul-uf** [aimacode/aima-python#54]
`infinity` in `utils.py` has been represented as `1.0e400`. We may not be encountering such huge numbers while going through AIMA but I believe it is better to represent it in a more [pythonic way](https://docs.python.org/3/library/functions.html#float).

**Comment by gokul-uf** [comment]
@tmrts PR fixes this issue

**Comment by tmrts** [comment]
The PR is #53 and the representation will be changed to `infinity = float('inf')` which also allows `-infinity` to be the negative infinity.

**Comment by norvig** [comment]
Good! Thanks gokul-uf and tmrts.
