### ISSUE TITLE
Pytest Warnings

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#545]
I am running Python 3.5.2. When I run pytest, I get a ton of warnings. I think most of them are because of unclosed files. The warnings come from the `learning`, `search` and `text` modules. Here is the pastebin link:

https://pastebin.com/eHMZkdjm

Any ideas on how to combat this?

**Comment by norvig** [comment]
If there's a way to turn that warning off, we should do that.

Another possibility would be to make AIMAFile do

     with open(aima_file) as f:
         yield from f
so it would be returning an iterator over lines, not a file object, and it would be closing it properly. If we go that route, then we need different names: not AIMAFile and DataFile, but something that reflects the new usage, maybe AIMAFileLines and DataFileLines ... or some better names.

**Comment by MrDupin** [comment]
There is a way to turn off warnings, but it only works if the user uses `pytest` from a specific directory. By putting a `pytest.ini` file with the following lines:

```
[pytest]
filterwarnings =
    ignore::ResourceWarning
```

in the directory the user will run the pytest suite from, there will be no warnings of the nature mentioned above.

For example, if I put the above file in the `tests` directory and I run pytest from that directory, there are no warnings shown.

So, one option is to add the file to `tests` and suggest that the user run pytest from the tests directory.

**Comment by norvig** [comment]
OK, let's do that, and see if there are remaining problems.

**Comment by norvig** [comment]
Also, while we're here: do we really need `AIMAFile`? What files do we need to read that are not data files? If we don't need it, let's eliminate it.

And `DataFile` was named in the days when `file` was a builtin function. Now that `open` is recommended, maybe change `DataFile` to `open_data` or something like that?

**Comment by MrDupin** [comment]
I made the adjustments in #547. Note that `pytest.ini` doesn't have to be in tests, it can be in the aima-python directory too. I can change it if it's more useful in there.

**Comment by norvig** [comment]
Should `pytest.ini` be in both places, to give users more flexibility? I'm just trying to minimize user mistakes/confusion.
