### ISSUE TITLE
Dataset Visualization

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#563]
I am visualizing the iris dataset in the notebooks, but there is the issue of matplotlib code. Students don't really need to see it as it doesn't add anything and it is quite lengthy. Also, I want to visualize multiple combinations of properties so that readers can have a better feeling of how the dataset looks, so the code issue will be even worse.

One way around this is to simply store the visualizations as images and show them on screen without the code. We could give the sample code so that readers can run it on their own, but we wouldn't need to store the code for each combination.

Any ideas?

**Comment by Chipe1** [comment]
We can store the code in separate python file which contains code for similar purpose, like show MNIST.

**Comment by MrDupin** [comment]
Do you mean creating a new python file just for visualizations?

I quite like this idea.

**Comment by Chipe1** [comment]
Yes. Maybe rename canvas.py as it was created for the same task

**Comment by norvig** [comment]
Excellent advice @Chipe1 -- I think this makes things a lot cleaner. Students can go read this canvas.py /notebook.py file if they want, but because it is just imported, they will know that it is not necessary to read it.
