### ISSUE TITLE
N-Gram Models of Text Not Working Properly

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#572]
The `samples` function in `NgramModel`, which should be returning random sentences according to the given model, does not work correctly. The first word it returns is always the first word of the input, regardless of the word's probability.

I believe that is because the starting conditional probability, for the empty-string tuple ('', '', ...), only contains the first word.

I am working on a fix, but I am having trouble following the code. If anyone can help, it would be much appreciated.

UPDATE: I fixed the issue by rewriting part of the code for ngram. I will push the PR for review once #571 is accepted, to avoid conflicts.

UPDATE 2: The PR is #573.

**Comment by Chipe1** [comment]
Shouldn't we reset the prefix at the start of every new sentence? That way all words which may start a sentence would be included in the conditional probability for `('',)*(n - 1)`. If you are ok with this solution I'll make the changes.

**Comment by MrDupin** [comment]
I'm not sure I understand what you mean. `samples` returns just one sentence of a given length. That sentence currently only begins with the first word in the training data.

Do you mean reset the prefix when *adding* sequences to the probabilities table? I think that works.

**Comment by MrDupin** [comment]
After some debugging, here's the issue:

Say we have n=3 and the first word of the text is "flatland". If we take a look at the conditional probabilities we have, here's what we get.

We have ('', '', 'flatland'), but we have no other ('', '', WORD_HERE) probability. So, when we are starting to build a sentence, "flatland" will always get picked first since it is the only word preceded by two empty strings.

A fix to this would be to find the probabilities for each word appearing first, which should be the probability of the word appearing alone in general.

@Chipe1: Do you think you can do that? I want to go a different route and rewrite most of the code of the models (since I have a feeling what we have is an overkill). I think we should have implementation closer to Markov chains, which is heavily mentioned in the book. But I'm not 100% sure this will give an adequate result, so I would also like a back-up.
