### ISSUE TITLE
installation requirements without anaconda

### ISSUE THREAD

**Issue by avdd** [aimacode/aima-python#585]
I already have a local python infrastructure set up and am not enamoured of duplicating it with anaconda.

What are the requirements to run the notebooks?  So far I've figured out I need matplotlib, and something called ipywidgets, which I needed to enable in my jupyter environment.  Is there anything else?

**Comment by Chipe1** [comment]
There is one more requirement "networkx" specified in requirements.txt
Best run the notebook and see if there are any errors. We've not documented all the requirements yet.

**Comment by reachtarunhere** [comment]
There are little to no external dependencies. Once in the project directory just do:

`pip install -r requirements.txt` to install both Jupyter and networkx. 

You might need to use sudo depending on your setup.
