### ISSUE TITLE
A Repository for JavaScript

### ISSUE THREAD

**Issue by duaraghav8** [aimacode/aima-python#60]
Will AIMACODE consider setting up a repository for JavaScript as well? I think JS implementations of the algorithms, especially the search-based and NLP-based, would be a great idea. If a repo is created, JS coders can start contributing as well.

**Comment by norvig** [comment]
Excellent idea! I don't have the time to do any work on the JS repository myself, but I'm glad to open it up.

**Comment by duaraghav8** [comment]
Thank you, I'm already on it!

**Comment by norvig** [comment]
Repository has been created.
