### ISSUE TITLE
Non-Uniform Representation of Coordinates/Points

### ISSUE THREAD

**Issue by reachtarunhere** [aimacode/aima-python#61]
Most of the code uses tuples to represent points (example: search.py). The new utils.py treats points as objects as attributes x and y and tends to use a.x,a.y for the coordinates. This can be observed in the distance function.

This was done so as to account for https://www.python.org/dev/peps/pep-3113/ which removes support for parameter unpacking in Python3. 

@norvig So a decision needs to be made regarding the representation of points. I feel we can use tuples but manually unpack them at the beginning of the functions. If we do this I can send a PR right away making the required changes.

**Comment by norvig** [comment]
Good question. It is a shame that Python doesn't have a fixed answer. I see three main choices:

(1) tuple: (x, y) pair; manually unpack. 
    def Point(x, y): return (x, y)
    def X(point): return point[0]
    def Y(point): return point[1]

(2) Named tuple:
    Point = collections.namedtuple('Point', 'x, y')

(3) Complex numbers -- good for representing points in the (float x float) plane; for example the distance function is just "def distance(A, B): return abs(A - B)". Not so good for ints, though.

I think for simplicity it is probably best to go with (1).  In most places you are right, and we will do:

def f(point):
    (x, y) = point
    ...

But good to have the X and Y functions when needed, like for sort(points, key=Y).

**Comment by reachtarunhere** [comment]
I'll send a PR for making the change and adding all 3 functions Point, X, Y.
