### ISSUE TITLE
%psource

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-python#613]
We use %psource in notebooks to refer to code, and that is good. But the code is displayed in a popup window, and one drawback is that you can only display one function at a time this way. Another drawback is that the code doesn't scroll with the rst of the document (this can sometimes be an advantage, sometimes a drawback).

I propose to add to utils the following function, and prefer to use it over %psource:

```
import inspect

def psource(*functions):
    "Print the source code for the given function(s)."
    print('\n\n'.join(inspect.getsource(fn) for fn in functions))
```

**Comment by MrDupin** [comment]
PR #614 takes care of this. I decided it was better to add the function to `notebook` instead of `utils`, to keep utils for implementation only stuff.

**Comment by VishnuDuttSharma** [comment]
@MrDupin I want to add a beautified version of the commit you made. Can you help me out with the process?

**Comment by MrDupin** [comment]
Sure, how can I help?

On the code, I would suggest you join on two newlines ( `'\n\n'.join ...` ) instead of none. It looks better to have the functions separated.

My only concern is whether or not `pygments` ships with Python or if the user will have to install it themselves. We try to keep the repository as free from external libraries as possible.

If you need anything else, feel free to ask.

**Comment by VishnuDuttSharma** [comment]
I think it should not be a problem, since this is required as a feature for notebooks and notebooks are generally installed using anaconda. 
However, to be on safe side, should I put it in a try-except block, depending upon availability of `pygment`?

**Comment by MrDupin** [comment]
I like this idea, yes. If pygments is installed, use that, otherwise use the default one.

I think this very useful since syntax highlighting is very important for a lot of people, so I suggest you make a PR after your changes and let Mr. Norvig decide. It looks good to me though.

**Comment by MrDupin** [comment]
Since the PR got merged, I believe this can be closed.

**Comment by norvig** [comment]
Thanks for the good work on this!
