### ISSUE TITLE
Test cases for random functions

### ISSUE THREAD

**Issue by Chipe1** [aimacode/aima-python#627]
I thought using `random.seed()` would fix the problem by making the tests repeatable, but in #626 changing a linein README.md caused the output (on travis) to change.
Am I using the random.seed incorrectly or are there other factors at play?

**Comment by MrDupin** [comment]
I have noticed that too. Quite a while ago I tested `random.seed` for the Neural Nets and locally the same result was always occurring, but on Travis it occasionally fails. I'm not sure why that happens. It is hard to look into since access to a Travis CI is hard to come by.

**Comment by MrDupin** [comment]
I added more tests for the neural networks in #630. We would have to be very, very unlucky to fail this now. More than 6 of the 9 tests need to fail for the assertion to crumble, which I don't see happening.

For random forest, maybe we could do something like `assert test in ['setosa', 'virginica', 'versicolor']`. It's not great, but if the implementation breaks we will catch it.

We can alternatively do something like

```
assert test1 == 'setosa' or test2 == 'setosa'
assert test3 == 'virginica' or test4 == 'virginica'
assert test5 == 'versicolor' or test6 == 'versicolor'
```

So for each class we have two tests. I doubt both will fail at the same time.

**Comment by Chipe1** [comment]
Kind of defeats the purpose of testing.

**Comment by MrDupin** [comment]
Well, part of testing is to see if something breaks, which we still cover.

**Comment by MrDupin** [comment]
I also want to note that in `csp` we also have a test randomly failing (`min_conflicts`).

@norvig: How do you think we should deal with this? Maybe we can run *n* tests and assert that at least 75% (or something) of them should pass. We already do that with some of the learners, so it might be worth expanding it for more functions.

**Comment by MrDupin** [comment]
This can be closed now.
