### ISSUE TITLE
MNIST compatible data set

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-python#636]
It would be good to incorporate this data set, which has the same format as MNIST, and so should be easy to work with: https://github.com/zalandoresearch/fashion-mnist/blob/master/README.md

**Comment by MrDupin** [comment]
I agree, it would fit perfectly into `learning_apps.ipynb`. I will take a look the next couple of days to see where we stand performance-wise and if it's possible to work with it.

**Comment by MrDupin** [comment]
I have added the files in #646.

The functions `show_MNIST` and `show_ave_MNIST` need to also be updated so that the classes are appropriately named.

**Comment by norvig** [comment]
Thanks!
