### ISSUE TITLE
aima-data submodule is outdated

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#638]
The [aima-data submodule](http://imgur.com/NElSrLs) is a bit outdated. I am not sure if I'm doing something wrong, but when I run:

```
git clone https://github.com/aimacode/aima-python.git

cd aima-python
git submodule init
git submodule update
```

as per the [instructions](https://github.com/aimacode/aima-python/blob/master/CONTRIBUTING.md#running-the-test-suite), `pytest` fails because there is data missing.

I think the submodule should be updated, but I'm not very familiar with how submodules work. There is the possibility the error is on my side too (outdated software, or maybe misunderstanding something).

**Comment by norvig** [comment]
I also don't understand how submodules work!

**Comment by MrDupin** [comment]
Works great now. Closing.
