### ISSUE TITLE
Key error bug in CustomMDP

### ISSUE THREAD

**Issue by nickaustinlee** [aimacode/aima-python#657]
mdp.ipynb has a class called CustomMDP. The example crashes because it seems to improperly assign State and Action to A, B, or None. 

The buggy code is somewhere here: 

    def __init__(self, transition_matrix, rewards, terminals, init, gamma=.9):
        # All possible actions.
        actlist = []
        for state in transition_matrix.keys():
            actlist.extend(transition_matrix.keys())
        actlist = list(set(actlist))

        MDP.__init__(self, init, actlist, terminals=terminals, gamma=gamma)
        self.t = transition_matrix
        self.reward = rewards
        for state in self.t:
            self.states.add(state)

**Comment by nickaustinlee** [comment]
I fixed the bug. 

First, modify CustomMDP to be as follows: 

    def __init__(self, transition_matrix, rewards, terminals, init, gamma=.9):
        # All possible actions.
        actlist = []
        for state in transition_matrix.keys():
            actlist.extend(transition_matrix[state])
        actlist = list(set(actlist))
        print(actlist)

Next, swap the order of variables in the T function and add a None if statement. 


    def T(self, state, action):
        print("The action is %s " % action)
        print("The state is %s " % state)
        if action is None:
            return [(0.0, state)]
        else:
            return [(prob, new_state) for new_state, prob in self.t[state][action].items()]

**Comment by MrDupin** [comment]
I haven't done much work in that notebook, but this looks nice. I suggest you make a Pull Request.

Thanks!
