### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by diegorodriguezv** [aimacode/aima-python#662]
Hello everyone. Amazing repo!
I noticed a small typo in csp.ipynb:
> Now let us check the total number of assignments and unassignments which is the length ofour assignment history.

Should be:
> Now let us check the total number of assignments and unassignments which is the length **of our** assignment history.

Should I submit a PR?
Thanks.

**Comment by MrDupin** [comment]
Yes, good catch!

**Comment by diegorodriguezv** [comment]
The other typo int he same file is:
> result  # A dictonary of assignments.

Which should be:
> result  # A dictionary of assignments.

Both are fixed in the PR.

**Comment by DheerajMalisetty** [comment]
I have fixed both typo bugs. But, I am getting an error
![screenshot from 2018-01-14 15-13-12](https://user-images.githubusercontent.com/32234121/34914691-a4bb431e-f93d-11e7-8cea-1ff28c97d771.png)

**Comment by DheerajMalisetty** [comment]
Is it a problem.
Thanks

**Comment by MrDupin** [comment]
Closing and reopening your PR might fix this.

**Comment by DheerajMalisetty** [comment]
Ok sir. But, Is the pull request sent by me will be closed or merged?

**Comment by MrDupin** [comment]
Closing and reopening a PR simply restarts the testing suite. It is up to Mr. Norvig to merge or reject the PR.
