### ISSUE TITLE
Small typo in learning.ipynb

### ISSUE THREAD

**Issue by aswanipranjal** [aimacode/aima-python#673]
Hello, all. I've been going through the notebooks to understand how the algorithms work. I noticed a small typo in the Gini impurity part in [learning.ipynb](https://github.com/aimacode/aima-python/blob/master/learning.ipynb) :
```
We select split which minimizes the Gini impurity in childre nodes.
```
It should be:
```
We select split which minimizes the Gini impurity in child nodes.
```

Can I submit a PR correcting them?

Awesome job on the Repo, btw.
Thank you!

**Comment by MrDupin** [comment]
I think it should also have an 'a' before 'split'.

Yes, you can make the PR. Nice catch.
