### ISSUE TITLE
Placement of cell in search.ipynb

### ISSUE THREAD

**Issue by apb7** [aimacode/aima-python#674]
@norvig and @MrDupin: The visualization cell of `uniform_cost_search` in `search.ipynb` has been misplaced under the 'A* Search' header instead of the 'Uniform Cost Search' header.  
Shall I correct this with a PR?  
Thanks!

**Comment by MrDupin** [comment]
Yes, good catch.

**Comment by apb7** [comment]
@norvig and @MrDupin: In `search.ipynb`, in the list under the header of 'Searching Algorithms Visualization', Best First Graph Search and Uniform Cost Search (Points 5. and 6.) have been placed before Depth Limited Search and Iterative Deepening Search (Points 7. and 8.). Since the list places Uninformed Search Algorithms before Informed Search Algorithms, should we interchange the order of the above-mentioned algorithms i.e. Best First Graph Search and Uniform Cost Search with Depth Limited Search and Iterative Deepening Search?  
Thanks!

**Comment by apb7** [comment]
Since this issue has been addressed with PR #670, I am closing it.  
Thanks @norvig and @MrDupin!
