### ISSUE TITLE
Repetition of best_first_graph_search function in search.ipynb

### ISSUE THREAD

**Issue by apb7** [aimacode/aima-python#678]
@norvig and @MrDupin: In `search.ipynb`, to implement the visualization of Uniform Cost Search and A* -Search, the `best_first_graph_search` function has been written twice - first for the visualization of Uniform Cost Search and then for A* - Seach.  
We can use the same function for both the Uniform Cost Search as well as the A* - Search since both searches differ with respect to the heuristic estimate to the goal.  
Thanks!

**Comment by apb7** [comment]
Hello @MrDupin! Shall I close this if it seems to be a trivial issue? 
Sorry for the inconvenience caused! Thanks!

**Comment by MrDupin** [comment]
Sorry it took so long to respond. Yes, removing any repetition would be great. You can use the auxiliary file [`notebook.py`](https://github.com/aimacode/aima-python/blob/master/notebook.py) to store the function. (`notebook.py` is used to store code that the reader doesn't need to see - for example visualization code)
