### ISSUE TITLE
Adding to learning.ipynb

### ISSUE THREAD

**Issue by aswanipranjal** [aimacode/aima-python#682]
Hello @norvig and @MrDupin, currently the Decision Tree Learner part in `learning.ipynb` does not contain any examples of how the algorithm works. There aren't any applications of the Decision Tree Learner in `learning_apps.ipynb` either. I was thinking that maybe to better describe the Decision Tree part, we could add a sample example of how it will perform with iris dataset and what it may learn. 
I was also thinking that maybe we could add some tree graph visualisations, generated using networkx, to show how the tree is actually created and what it learns in each step. Something like these [tree-graphs](https://github.com/aswanipranjal/aima-python/blob/decision-tree-test/DecisionTreeLearner%20Test.ipynb) at the end of the notebook (I still have to do some clean-up).

**Comment by MrDupin** [comment]
I like this idea, especially since the `networkx` library is something already used in the repository. Sounds good!

**Comment by norvig** [comment]
That would be great!

**Comment by aswanipranjal** [comment]
Hey @MrDupin, There has been a mistake from my side. I didn't realise but the graph that I am generating also uses `pygraphviz` which in turn uses `graphviz`. 
Another mistake was that I didn't notice, but in [the graph](https://github.com/aswanipranjal/aima-python/blob/decision-tree-test/DecisionTreeLearner%20Test.ipynb) for the iris dataset, the branches for **Sepal Length** and **Sepal Width** have similar values for *virginica* and *versicolor* which cannot be differentiated properly.

I am sorry about these. Should I just add an example for the DecisionTreeLearner with the iris dataset?

**Comment by MrDupin** [comment]
Hmm, I suggest you make the simple PR of adding examples for the Decision Tree Learner and open an issue for adding graphviz in the dependencies, and take it from there.
