### ISSUE TITLE
Error loading search.ipynb

### ISSUE THREAD

**Issue by apb7** [aimacode/aima-python#688]
On opening search.ipynb, the following error occurs:  

![screenshot-localhost-8888-2018-01-11-10-30-03-094](https://user-images.githubusercontent.com/24826041/34879544-9a03d4e2-f7d3-11e7-9fd1-912a62f7e9fb.png)

**Comment by nvinayvarma189** [comment]
I think somebody has got merge conflicts in the file - those <<< and === and >>> lines are how git shows its merge conflicts. To make it valid, clearing the merge conflicts.


```
<<<<<< HEAD
   Either keep this line...
=======
   ... or this one. But not both!
>>>>>>> a1f5acbaa00bc1b1e5fc3532ba19a013a271542c
```

and also remove the lines having  '<<<<<< HEAD',  '=======',  '>>>>>>> a1f5acbaa00bc1b1e5fc3532ba19a013a271542c'. Those are the git conflict makers.

and then [nbdime](http://nbdime.readthedocs.io/en/stable/) can be used to avoid git doing that again. I hope this solves the issue.

**Comment by apb7** [comment]
Hello  @nvinayvarma189! Thanks for the help! But I think this issue has been resolved with PR #689 (though the PR hasn't been merged yet). 
Thanks!

**Comment by nvinayvarma189** [comment]
Oh sorry, I did not look at it. Thanks for letting me know.

**Comment by nvinayvarma189** [comment]
Hey @apb7 I find the PR for this issue is still not merged. I see all the checks have passed but, is there any problem still not solved ?

**Comment by apb7** [comment]
Hi @nvinayvarma189! The PR will be merged by @norvig.  
Thanks!
