### ISSUE TITLE
Improved explanation of genetic algorithms using an example

### ISSUE THREAD

**Issue by ad71** [aimacode/aima-python#696]
I made an [example](https://github.com/ad71/aima-python/blob/master/search.ipynb) in the search.ipynb notebook explaining the intuition behind genetic algorithms and how the existing functions in search.py can be understood and used for other problems, as the current notebook didn't explain the functions well. It is a simple phrase generation problem. I have tried my best to explain step-by-step how one can solve the problem using the existing functions. I have also implemented a well commented [GUI version](https://github.com/ad71/aima-python/blob/master/gui/genetic_algorithm_example.py) for students to play around with. I would like some feedback on my work and whether I should submit a PR

**Comment by apb7** [comment]
Hello @ad71! We prefer not to use third party libraries and make the code as independent as possible. For implementing the GUI, you have used Pygame. Can you instead use Tkinter which comes bundled up with Python 3?  
Thanks!

**Comment by ad71** [comment]
@apb7 thanks for the reply! I have no experience with Tkinter, but I can sure give it a try as the program itself is pretty straightforward. But before I start working, I need to know if this will be a useful contribution or should I start working on something else?

**Comment by apb7** [comment]
@ad71: I think @norvig and @MrDupin will be able to help you out here.  
Thanks!

**Comment by MrDupin** [comment]
The explanation is a nice addition to the notebook, but I agree that using pygame is not that great. If you could do it in Tkinter, it would be awesome.

**Comment by ad71** [comment]
Sure! I'm on it.

**Comment by ad71** [comment]
I have converted the example to tkinter. [This](https://github.com/ad71/aima-python/blob/master/gui/genetic_algorithm_example.py) is the final GUI version, and [this](https://github.com/ad71/aima-python/blob/master/search.ipynb) is the final python notebook. Should I submit a PR?

**Comment by MrDupin** [comment]
Yes, you should submit a PR. Nice work!
