### ISSUE TITLE
Add tests for Zebra Problem and Nqueens Problem in test_csp.py

### ISSUE THREAD

**Issue by Dragneel7** [aimacode/aima-python#703]
Currently there are no tests written for the two algorithms that have been implemented in the file csp.py .
@MrDupin Should we add the tests for these two algorithms.
Thanks.

**Comment by MrDupin** [comment]
Sure, go ahead. Make sure though the tests don't take too long to run.

**Comment by dubesar** [comment]
@antmarakis I think the tests are already added in the test_csp.py file. Please close this issue.
