### ISSUE TITLE
Implementing a stochastic game example(Backgammon) in games.py

### ISSUE THREAD

**Issue by AdityaDaflapurkar** [aimacode/aima-python#705]
The Expectiminimax algorithm from the chapter 'Adversarial Search'(section : stochastic games) is not implemented in games.py. Also, it is not added to the list of algorithms. Should I work on it's implementation?

**Comment by ad71** [comment]
As far as I know, expectiminimax is not an algorithm. It is a (mathematical) function that "generalizes the minimax value for deterministic games to an expectiminimax value for stochastic games". It is something like a heuristic for stochastic games and (as far as I know) isn't used by the currently implemented algorithms in games.py
Correct me if I'm wrong.

**Comment by AdityaDaflapurkar** [comment]
Yes, you are right @ad71 . It is not an independent algorithm but just a variant of minimax algorithm for stochastic games. Currently there isn't any implementation for a stochastic game in games.py. Thus Expectiminimax is not used anywhere. @MrDupin ,will it be good if I try implementing a stochastic game(Backgameon) in games.py? I will update this issue accordingly.

**Comment by MrDupin** [comment]
Sure, sounds good!
