### ISSUE TITLE
EightPuzzle move list is wrong

### ISSUE THREAD

**Issue by PeterDrake** [aimacode/aima-python#709]
On line 425 of search.py:

move = {0:[1,3], 1:[0,2,4], 2:[1,5], 3:[0,6,4], 4:[1,3,5,7], 5:[2,4,8], 6:[3,7], 7:[6,8], 8:[7,5]}

Position 7 (bottom center) should have three neighbors, not two; the missing one is 4.

**Comment by ad71** [comment]
Yes sir, you are right. I have submitted a patch.

**Comment by JaeDukSeo** [comment]
So is this still a problem? or can we close it?

**Comment by ad71** [comment]
We can close this, but the eight puzzle class is still messed up. See #785
