### ISSUE TITLE
EightPuzzle code is not consistent with rest of search.py

### ISSUE THREAD

**Issue by PeterDrake** [aimacode/aima-python#710]
The various search algorithms seem to want problems to be defined as subclasses of Problem,
but EightPuzzle is some kind of odd stand-alone section with its own solve method.

It also immediately follows a comment "A* heuristics", but there are no heuristics specified.

**Comment by SasankYadati** [comment]
Hello, I would like to take this up. I previously wrote code for 8puzzle using A* Search and I think I can work on this. Thank you.

**Comment by SasankYadati** [comment]
@PeterDrake The heuristics used by A* Search algorithm really depend on the problem (environment) right? So we can't really have single heuristic function that works. I think a default heuristic should be part of the EightPuzzle class and there should be an option for the user to pass his own heuristic function.

**Comment by PeterDrake** [comment]
I think heuristics should be stand-alone functions, as one might try more than one heuristic for a given problem (e.g., misplaced tiles or Manhattan distance for the 8-puzzle).

**Comment by SasankYadati** [comment]
Hmm. But we cannot use misplaced tiles or Manhattan distance in many other problems, right? What if we have one heuristic for each problem (if applicable) and also provide a way for the users to have their own heuristics? I rewrote the EightPuzzle class. It is now derived from Problem class. I have defined heuristic function as the number of misplaced tiles in a given state.

**Comment by PeterDrake** [comment]
Providing a default and allowing users to specify their own sounds reasonable. Perhaps it would be good to include one (Manhattan) as an example? It could be given a name indicating that it's only applicable for the 8-puzzle. (I suppose, if written properly, it would also work for the 15-puzzle.)

**Comment by SasankYadati** [comment]
Perfect. I just made a pr with the same changes. However, I used number of misplaced tiles as the default heuristic function.
