### ISSUE TITLE
NQueensProblem doesn't work with search methods

### ISSUE THREAD

**Issue by PeterDrake** [aimacode/aima-python#711]
If I `import search` and then
```
puzzle = search.NQueensProblem(8)
print(search.breadth_first_search(puzzle))
```
I get:
```
TypeError: unhashable type: 'list'
```
In order to work with the various search algorithms, the states have to be tuples, not mutable lists.

**Comment by BraveNewPumpkin** [comment]
same issue. Please make NQueensProblem or NQueensCSP work with astar_search, forward_checking, etc.

**Comment by ad71** [comment]
I have submitted a patch and NQueensProblem will now be compatible with `graph_search`, `depth_first_graph_search`, `breadth_first_search`, `best_first_graph_search`, `uniform_cost_search` and `astar_search`. Sorry for the inconvenience.

**Comment by norvig** [comment]
The fix should be to make the `NQueensProblem` produce tuples, not to make `search` coerce states to tuples.

**Comment by ad71** [comment]
I completely forgot about this issue until now. I assign myself the task of fixing this problem and rewriting the notebook section of NQueensProblem.
