### ISSUE TITLE
Add DLS and IDS to search notebook

### ISSUE THREAD

**Issue by nvinayvarma189** [aimacode/aima-python#712]
I would like to add the examples for depth limited search and Iterative deepening search.

**Comment by nvinayvarma189** [comment]
@MrDupin  is it advisable to implement these algo's in the romania map or adding a tree visualisation is needed(in the book the algo's are explained with trees without loops). Can you help me in this.
Thanks.

**Comment by MrDupin** [comment]
Since the Romanian map is the one heavily used in the book and examples, I suggest you run the algorithms on that. If possible, it would be really useful to visualize the intermediate steps.
