### ISSUE TITLE
improve search.ipynb

### ISSUE THREAD

**Issue by nvinayvarma189** [aimacode/aima-python#714]
Hey  @MrDupin , @norvig . I found that I actually implemented greedy best first search algo in my PR #708. So I want to make changes and make it greedy best first search algo and as all the uniform cost search, greedy best first search, a* algos use best first search algo, I would like to remove the repetition of best first algo in the search.ipynb (repeated thrice).
I would also like to add some short documentation explaining the differences between them so that these algorithms will be easily understandable for others. Is it advisable to continue?
Thanks.

**Comment by MrDupin** [comment]
Sounds good. I think the `search` notebook needs an overhaul in general. I will probably create an issue about this next week, but I think the notebook suffers from a lot of repetition and lack of proper structure. If you could cut down on the repetition, it would be great.

Don't forget that you can use `notebook.py` to store notebook code that the reads don't really need to see (for example, visualization code).

**Comment by apb7** [comment]
Hello @MrDupin, I had already created an issue regarding the repetition problem #678. I think we can work on that.  
Thanks!

**Comment by MrDupin** [comment]
@apb7: Ah yeah, I forgot. Great then, I think cleaning up the `search` notebook is top priority, so that we can more easily move in the future.

**Comment by apb7** [comment]
@MrDupin: I think this issue has been fixed in PR #716. We should close it.  
Thanks!
