### ISSUE TITLE
Add examples and tests for AdaBoost algorithm

### ISSUE THREAD

**Issue by aswanipranjal** [aimacode/aima-python#728]
Hey @norvig, @MrDupin: currently, the `learning.ipynb` notebook lacks an example for **ensemble learning**. Since the `perceptron` classifier gives an accuracy of almost 68.8% (not a weak learner though) on the **iris** dataset, I was thinking that maybe we can use it to add an example for **AdaBoost algorithm** and show how it works. We can also add code for **decision stump**, but since its pseudo code has not been provided maybe we can go with the perceptron classifier?
I also wanted to add some tests for **AdaBoost**.

What do you think?

**Comment by MrDupin** [comment]
Since the Perceptron is an algorithm pretty much everyone learns when studying machine learning, I think using it as an example is for the best. It is simple and easy to use, so I would personally go with it.

Adding tests is great.
