### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-python#73]
We need to update all the files to Python 3. Issues include: print is now a function; range and map and other functions no longer produce lists; objects of different types can no longer be compared with <; strings are now Unicode; it would be nice to move % string formating to .format; there is a new next function for generators; integer division now returns a float; we can now use set literals; legacy functions such as `every` should be replaced with Python 3 functions such as `all`, or by generator expressions or comprehensions.

**Comment by light94** [comment]
Hi @norvig ,
I want to work on this if no one has taken this up yet.

**Comment by norvig** [comment]
Great work; the code now passes Python 3 build/test. But there are some outdated idioms that should be replaced eventually.

**Comment by anuj1995** [comment]
I want to work on it

**Comment by rusrushal13** [comment]
Is this issue is still Open?

**Comment by SnShine** [comment]
Nope. This problem's solved already.
