### ISSUE TITLE
Move from inline doctest to separate _test.py files.

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-python#74]
Currently, many functions have doctest tests in their docstrings. That should be changes so that the tests are in a separate `filename_test.py` file, and are in the form of asserts, suitable for py.test, not doctest. Why is this better? Makes the code in the .py files more condensed; easier to read. Puts all the tests in one place, not interrupting the flow of the code.

**Comment by gokul-uf** [comment]
@norvig I am working on this

**Comment by norvig** [comment]
OK, we decided it is ok to have one doctest example to explain usage of a function; other tests shoud move to `_test.py` files.  But how do we convince the test framework to run the doctests?

**Comment by Chipe1** [comment]
We can have a copy of the doc test in test_*.py
