### ISSUE TITLE
Add Learning Agent to vacuum_world.ipynb

### ISSUE THREAD

**Issue by apb7** [aimacode/aima-python#741]
Hello, @norvig and @MrDupin! Currently, `vacuum_world.ipynb` discusses all the basic kinds of agent programs that embody the principles underlying almost all intelligent systems.  
I am planning to add an explanation and a schematic diagram of the learning agent in `vacuum_world.ipynb` as well.
Please suggest.  
Thanks!

**Comment by MrDupin** [comment]
I am not familiar with `agents.py`, does the learning agent have an implementation? I didn't find something. Also, can a learning agent be found in the book? If not, maybe you can implement the agent only in the notebook.

**Comment by apb7** [comment]
@MrDupin: Learning agent is given in the book as a `general learning agent`. It does not have an implementation in `agents.py`. I have added it to the notebook in PR #742.  
Thanks!
