### ISSUE TITLE
Jupyter/Ipython notebooks

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-python#75]
Eventually, we want to have a `filename.ipynb` for each `filename.py`, where the Notebook will give examples and documentation for how to use the code.

**Comment by jeff3456** [comment]
Hi @norvig ,

I would like to take on the creation of iPython notebooks for each filename.py

What sorts of examples/ visualization should I implement? Am I free to choose the examples or should they be directly from the book?

**Comment by norvig** [comment]
Anything that explains how to use the code. When there are examples from the book, great -- but not necessary.

**Comment by reachtarunhere** [comment]
@norvig do you think that having gui like simulations will be useful. I think these can be helpful and fun to play with. For example in case of Chapter 2 we can allow implementing a grid world for the vacum robot. Also we can have a visualizations of different searches where user can make use of IPython's %debug to go step by step through the code and see how the frontier is building etc. If you like these ideas I would love to start working on them.

**Comment by norvig** [comment]
Yes, I like this idea. I don't know enough about IPython to know if it can
be done well there, or has to be done in javascript. If you can do it in
IPython, I'm all for it.

**Comment by reachtarunhere** [comment]
I guess we can do some of them without making use of JS. In some examples we might require embedding JS to add interactivity. I will give it a shot and see what I can hack around without using JS at all.

**Comment by norvig** [comment]
See what you can do. I have nothing against embedding JS in Notebooks -- my
question was whether the notebook framework was so limiting that it would
be easier to have an all-javascript/html/css page without the notebook. But
if you can make things work in the notebook, that would be great.

**Comment by gokul-uf** [comment]
@norvig IPython/Juypter notebooks do not provide facilities to use interactive animations out of the box. By interactive animations, I am referring to buttons .etc not dragging or rotating a 3D plot, for example. This functionality can be provided by JS. However, I have not seen examples where JS has been integrated into IPython notebooks. To ensure that code and visualizations are not separate and to allow people to play around with the notebook, we could instead use a series of static images (one for each iteration, perhaps?).

REFS:
1. http://jakevdp.github.io/blog/2013/05/12/embedding-matplotlib-animations/
2. https://jakevdp.github.io/blog/2013/06/01/ipython-notebook-javascript-python-communication/

**Comment by reachtarunhere** [comment]
@gokul-uf My idea when I planned to do it without js is exactly the same of what you mentioned (changing static images). We could use embedding JS as a last resort.

**Comment by norvig** [comment]
I've seen the animations; they are cool, but are limited in that you can't interact with them -- you can use an animations to, say, show how the frontier expands in a search, or how the Serpinski triangle unfolds, but you can't play a game of checkers where a human player alternates move with the computer.

**Comment by reachtarunhere** [comment]
@norvig Please give these a look.
https://jakevdp.github.io/blog/2013/12/05/static-interactive-widgets/
https://github.com/ipython/ipywidgets

So there are these widgets that can allow buttons,sliders (basically a GUI inside a notebook). I haven't an IPy notebook for making something along these lines before. I am exploring these and from the demos it does not seem that it should be too difficult to implement (take that with a grain of salt as I haven't tried them yet).

**Comment by reachtarunhere** [comment]
@norvig From the few examples I played with yesterday I can confirm the IPy notebook will not be limiting to the implementation. Basically it is possible to bind each event like click etc. on a DOM element such that it invokes some python code. This is very simple using a bulit-in function call which injects code into the kernel running the notebook. So we will still need to make the basic UI with html/css/js but as the events can invoke python code our orignal code can act as logic for the game.

**Comment by jeff3456** [comment]
@reachtarunhere That's good to hear! So do you suggest we use one of the packages you mentioned? I could certainly try them out as I am planning moving forward with creating the first notebook for agent.py

**Comment by reachtarunhere** [comment]
@jeff3456 Yes, we can use those packages. A lot will depend on what simulation/demos we want to put in. In some cases it may be required to write a custom widget too. I had some plans to work on agents.py too but its ok if you want to take that up. I will take up the work on search.py file instead. If you get stuck somewhere and need my help with the widgets etc. feel free to comment here or drop me a mail. Cheers :)

**Comment by jan-rudolf** [comment]
I am currently working on chapter 3 examples to Jupyter. 

Besides widgets, it's also possible to add JavaScript/HTML into Jupyter notebooks, so the interactivity with the user is not much limiting (checkers could be possible), but it takes more time to do it.

**Comment by reachtarunhere** [comment]
@jan-rudolf as I mentioned in my comment above yesterday I am working on search.py already. It would be great if you can take up something else.

**Comment by jan-rudolf** [comment]
@reachtarunhere ok, but this could involve chapters 3, 4 or 5. Which one do you have in mind?

**Comment by reachtarunhere** [comment]
@jan-rudolf I I am developing some common code to represent grids, graphs and do simulations. Thus this spans all of the search topics. I will try to put some stuff up and maybe we can collaborate once I have the basic structure ready. It would be best if you can take up some other IPy notebook in the mean time.

**Comment by jan-rudolf** [comment]
@reachtarunhere ok

@norvig What about to have notebooks named by chapters? For example search.py has classes and functions across several chapters. If we would have an example for every source code, it would be too long, not clear...

**Comment by norvig** [comment]
Hey @reachtarunhere , I will happy when we have the problem of notebooks being too long! If we get there, it would make sense to have notebook names like `CH3_search.ipynb`. But right now our problem is too little, not too much. And it doesn't make sense quite yet to rename with chapter numbers, since we're not quite sure yet what will be the chapter numbering in fourth edition.

I'm really looking forward to seeing what you come up with for grids!

**Comment by reachtarunhere** [comment]
@norvig Sorry for the long delay. I have put up a very basic prototype [here](https://github.com/reachtarunhere/interactiveblocks). Please ignore some of the hacks and rough edges for now. I plan to clean them up soon. Also I have mentioned some more things that can be done. You need to download the zip file for now and open the IPy notebook in Jupyter to try it out.

**Comment by SnShine** [comment]
We need to have `ipythonblocks.py` (https://gist.github.com/jiffyclub/4499453) in the project folder, right?

**Comment by reachtarunhere** [comment]
@SnShine I am sorry I totally forgot to mention that one needs to install IPythonblocks via pip3.

**Comment by tolusalako** [comment]
I started work on [agents.ipynb](https://github.com/tolusalako/aima-python/blob/master/agents.ipynb). Am I headed in the right direction? Or should I include more details?
