### ISSUE TITLE
Add virtualenv installation details in CONTRIBUTING.md

### ISSUE THREAD

**Issue by umangahuja1** [aimacode/aima-python#754]
If someone is having both python 2.x and python 3.x, it becomes essential to create virtualenv to separate both.
Also new users who are not aware of this may feel stucked. 

This will help users to create virtual environment before getting started.

I will be adding a PR. See if it makes things easier for others. 

Any admin here to comment on this issue?

**Comment by MrDupin** [comment]
The PR got closed, so we do not need this anymore.
