### ISSUE TITLE
Missing POMDP value-iteration

### ISSUE THREAD

**Issue by ad71** [aimacode/aima-python#760]
mdp.py has no implementation of POMDP value-iteration. It cannot be directly implemented as we need to build a pomdp class. There are subtle differences between an mdp and a pomdp and I would like suggestions on whether to inherit from the mdp class or implement the pomdp class from scratch. @norvig @MrDupin what do you suggest?

**Comment by MrDupin** [comment]
I think building it from scratch is the better method, in my opinion.

**Comment by ad71** [comment]
I thought so too. I'll get to work as soon as my exams finish this week.
