### ISSUE TITLE
mdp_apps notebook

### ISSUE THREAD

**Issue by ad71** [aimacode/aima-python#766]
Hello @norvig and @MrDupin ! There are many standard problems that show how MDPs can be formulated and solved and I think adding these will help better explain the classes and methods in mdp.py. As the mdp notebook is already pretty cluttered, I do not want to add more examples there, instead I was planning to create a mdp_apps notebook for solutions to common real-world MDP problems before I start working on the POMDP section. Is it advisable to continue?

**Comment by MrDupin** [comment]
Sure, if you have some applications where mdp can be applied to, a `apps` notebook would be nice.
