### ISSUE TITLE
"from notebook import psource, pseudocode" doesn't work

### ISSUE THREAD

**Issue by yip8** [aimacode/aima-python#786]
"from notebook import psource, pseudocode" doesn't work.
```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-48829097b1db> in <module>()
----> 1 from notebook import psource, pseudocode

~/Desktop/aima-python-master/notebook.py in <module>()
      4 from games import TicTacToe, alphabeta_player, random_player, Fig52Extended, infinity
      5 from logic import parse_definite_clause, standardize_variables, unify, subst
----> 6 from learning import DataSet
      7 from IPython.display import HTML, display
      8 from collections import Counter, defaultdict

~/Desktop/aima-python-master/learning.py in <module>()
   1105 
   1106 orings = DataSet(name='orings', target='Distressed',
-> 1107                  attrnames="Rings Distressed Temp Pressure Flightnum")
   1108 
   1109 

~/Desktop/aima-python-master/learning.py in __init__(self, examples, attrs, attrnames, target, inputs, values, distance, name, source, exclude)
     96             self.examples = parse_csv(examples)
     97         elif examples is None:
---> 98             self.examples = parse_csv(open_data(name + '.csv').read())
     99         else:
    100             self.examples = examples

~/Desktop/aima-python-master/utils.py in open_data(name, mode)
    414     aima_file = os.path.join(aima_root, *['aima-data', name])
    415 
--> 416     return open(aima_file)
    417 
    418 

FileNotFoundError: [Errno 2] No such file or directory: 
```

**Comment by MrDupin** [comment]
Hmm, have you run

```
git submodule init
git submodule update
```

in your aima-python directory, [as per the installation guide](https://github.com/aimacode/aima-python/blob/master/README.md#installation-guide)? I think this might resolve the issue.

**Comment by yip8** [comment]
@MrDupin No it still happens. I am running jupyter notebook.

**Comment by ad71** [comment]
Have you downloaded from zip?
Retry cloning the repo using this command: 
`git clone --recurse-submodules -j8 git://github.com/aimacode/aima-python.git`
If this doesn't work, try
`git clone --recursive -j8 git://github.com/aimacode/aima-python.git`

**Comment by yip8** [comment]
I installed according to the installation guideline and have run 
`git submodule init
git submodule update`
I don't know if the problem is running jupyter notebook. I tried ipython notebook and it also does not work. Is running web-based notebook the way to open the notebook?

**Comment by MrDupin** [comment]
Did you write `git submodule init git submodule update` an an one-liner like this? They should be separated, run the one and then the other.

**Comment by yip8** [comment]
I solved the problem after upgrading some notebook dependencies to python 3.
