### ISSUE TITLE
NotJSONError when opening mdp.ipynb

### ISSUE THREAD

**Issue by bakerwho** [aimacode/aima-python#800]
Error text in Jupyter notebook:
```NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "r...',)```

Source appears to be intact, so I'm checking it for unclosed {}, etc.

**Comment by bakerwho** [comment]
This appears to be a common issue on Jupyter notebooks maintained using git. Check [this](https://github.com/jupyter/help/issues/67).

[nbdime](http://nbdime.readthedocs.io/en/stable/) appears to be a solution. Checking it out now.

**Comment by ad71** [comment]
This was because of minor merge conflicts due to #781 . I has been fixed now.
