### ISSUE TITLE
Add Forward-Backward to the probability.ipynb

### ISSUE THREAD

**Issue by Dimkoim** [aimacode/aima-python#813]
Hello Mr. @norvig, Mr. @MrDupin, and Mr. @delaray ! I would love to participate to the GSoC 2018 and what's a better start than fixing an issue. Currently the `probability.ipnyb` does not include any examples and info about the HiddenMarkovModel class and the Forward-Backward algorithm. I have prepared some updates and I will soon ask for a `PR`. 

Regards,

Dimitrios Koimtzoglou

**Comment by MrDupin** [comment]
Sounds good, I can't believe I missed HIdden Markov Models. I would say adding a notebook section on the subject is a great idea!
