### ISSUE TITLE
Incosistencies in return type of vectors in utils.py

### ISSUE THREAD

**Issue by goswami-rahul** [aimacode/aima-python#819]
The first function returns vector as `tuple` while the other as `list`.
Either both must return a `tuple` or a `list` for consistency.
```python
def vector_add(a, b):
    """Component-wise addition of two vectors."""
    return tuple(map(operator.add, a, b))


def scalar_vector_product(X, Y):
    """Return vector as a product of a scalar and a vector"""
    return [X * y for y in Y]

```
Should I put a PR to resolve this?
What should these functions return?

**Comment by ad71** [comment]
I think the first function returns a tuple because the code that calls it requires the returned data to be hashable, maybe to store it in a set? I might be completely wrong, but this is a common problem in some parts of the repository. You would need to find out which parts of the codebase call this function.

**Comment by goswami-rahul** [comment]
Yeah, it is possible that it may depend on the code where it is used.
However, I think it _shouldn't_ depend on how it is used.  Since it returns a vector, its type _must_ remain same throughout the code. It will lead to future conflicts.
The user can manipulate its type outside the function as he wishes.
For e.g., if the above function returns a tuple, and the user wants a list, he can simply do
```python
vec = vector_add(a, b)
vec = list(vec)
```
instead of changing the type in the function itself!
The main issue is that since both functions return _vectors_, both must be of the same type.

**Comment by bakerwho** [comment]
I'm not sure this should be messed with until we're certain exactly where
it's called. Consistency would be nice, but these functions are used widely
throughout the implementations. @ad71's point about hashing might be a
reason this is the way it is.

*Aabir Abubaker Kar*
*Physicist, Mechanical Engineer, etc*

**Comment by MrDupin** [comment]
I agree that consistency would be great. If you could find where the problematic functions are called, I would provide a more concrete answer. If the functions are called in code corresponding to pseudocode and it is required that they are of a certain type, then I am afraid it must stay as is to keep the code as close to the pseudocode. Otherwise, we can change the functions and then do casting as needed.

**Comment by goswami-rahul** [comment]
I have checked every usage of the above two functions (found their usages with PyCharm). I think the return type of `vector_add()` should be `vector` which is good. The following usage from `P_motion_sample()` verifies this:
```python
pos = vector_add(pos, v)
return pos + (orient,)
```
However, there are no such usages of the `scalar_vector_product()`  that can verify it to be `list`, as far as I have checked. I couldn't find any example where it _behaves_ like a `list`.
Same with this another function which returns `list`, but there's not any concrete usage to show its a `list`.
```python
def element_wise_product(X, Y):
    """Return vector as an element-wise product of vectors X and Y"""
    assert len(X) == len(Y)
    return [x * y for x, y in zip(X, Y)]
```
If we change their return type to `tuple`, only changes we will have to make are in their tests.

**Comment by MrDupin** [comment]
Then sure, you can make a PR fixing this. Changing them to tuples is fine.

**Comment by goswami-rahul** [comment]
I tried to make these changes in the functions and tests, but some other tests were failed due to this. The differences were reflected in many (6) functions like
```
  def test_inverse_matrix():
>       assert rounder(inverse_matrix([[1, 0], [0, 1]])) == [[1, 0], [0, 1]]
E       assert [(1.0, 0.0), (0.0, 1.0)] == [[1, 0], [0, 1]]
E         At index 0 diff: (1.0, 0.0) != [1, 0]
E         Full diff:
E         - [(1.0, 0.0), (0.0, 1.0)]
E         + [[1, 0], [0, 1]]
```
It now seems that we will have to leave them the way they are to avoid more bugs.

So, now should I close this issue?

**Comment by ad71** [comment]
There must be a reason why these functions are a certain way. I think you can close the issue.
