### ISSUE TITLE
Make the Build Pass!

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-python#83]
Build is failing; right now because map in logic.py returns a generator, not a list. We need to finish moving to Python 3 to make the build pass.

**Comment by tmrts** [comment]
There are a lot of  incompatibilities at the moment. This issue is essentially identical with #73

**Comment by Chipe1** [comment]
How to make it pass?
The py.test run fine for me . Is there some other tests to be done? How do I run the complete tests since I can see most error only after sending the pull requests.

Sorry for the noob questions

**Comment by SnShine** [comment]
Hey, all
I am working on this and here is my initial PR #94. Gonna add more modifications to that PR to make the whole repo pass build tests.
