### ISSUE TITLE
Invalid call to function [extra arguments] in learning.py

### ISSUE THREAD

**Issue by goswami-rahul** [aimacode/aima-python#830]
function `train_and_test` has prototype:
```python
def train_and_test(dataset, start, end):
```
but it is passed 4 arguments in the below function in learning.py.
```python
def learningcurve(learner, dataset, trials=10, sizes=None):
    if sizes is None:
        sizes = list(range(2, len(dataset.examples) - 10, 2))

    def score(learner, size):
        random.shuffle(dataset.examples)
        return train_and_test(learner, dataset, 0, size)
    return [(size, mean([score(learner, size) for t in range(trials)]))
            for size in sizes]
```
I think `learner` should not be passed, but then it is the only use of `learner` parameter  in `train_and_test`.
How should this be resolved?

**Comment by ad71** [comment]
Nice catch. This is definitely an error. Currently there are no tests for these functions and I'm sure it doesn't work the intended way. `score` is supposed to accept a learner and evaluate its performance on the given `dataset`. However, `train_and_test` just partitions the dataset into the training and validation sets. I'm sure this isn't the right function to call. Maybe this has something to do with `cross_validation` which is in a pretty unusable state as of now. #566 and #735 might be helpful. Hopefully @MrDupin can help.

**Comment by MrDupin** [comment]
The function `train_and_test` simply splits the data into training and testing set. I think it needs to be renamed though, to something like `train_test_split`.

Other than that, `learningcurve`, as with `cross_validation`, does not do much as mentioned by @ad71.

I suggest someone a) renames `train_and_test` and b) adds a note over the Cross Validation sections warning people that it is not usable and link to to [this issue](https://github.com/aimacode/aima-pseudocode/issues/55).
