### ISSUE TITLE
Add Random Forest to learning.ipynb

### ISSUE THREAD

**Issue by CharuChhimpa** [aimacode/aima-python#844]
@norvig and @MrDupin, Random Forest Algorithm is not added in learning.ipynb. Can I add that in the python notebook?

**Comment by MrDupin** [comment]
Sure, that would be a great addition! Make sure to add the section close to the Decision Tree One.

**Comment by CharuChhimpa** [comment]
@norvig, Can you please review my pr

**Comment by CharuChhimpa** [comment]
@MrDupin please review my pr

**Comment by CharuChhimpa** [comment]
@norvig and @MrDupin, I also find that the functions which are written for testing learners (eg : err_ratio, train_test_split, grade_learner and cross_validation) are no where explained in the python notebook. Are those needed to be added?

**Comment by MrDupin** [comment]
I will review your PR sometime tomorrow, I am a bit busy at the moment.

As for the evaluating functions, I don't think they need to be explained in the notebooks, their docstrings will do just fine.

**Comment by ad71** [comment]
@CharuChhimpa `cross_validation` isn't usable in its current state, nor are the functions that derive from it  (`learning_curve` for example). It won't be useful adding notebook sections for the functions that don't work. See #735 , #730 , #566 and [this issue](https://github.com/aimacode/aima-pseudocode/issues/55) for details. `train_test_split` just splits a dataset into the training and testing set. I can't imagine what a notebook section for this function might look like. You can go ahead if you have some ideas, but hold back on `cross_validation` for now.
