### ISSUE TITLE
Error in probability.ipynb

### ISSUE THREAD

**Issue by Noumanmufc1** [aimacode/aima-python#865]
Probability.ipynb notebook gives the follwing error on running:
![image](https://user-images.githubusercontent.com/35970677/37567702-7b29c7ba-2aec-11e8-9d9f-c8e8ee6122ef.png)

Does anyone know how to solve this?

**Comment by ad71** [comment]
There is probably a cell in the file that doesn't have the `execution_count` property. Open the .ipynb file in a text editor and check which cell is missing it. Maybe it has something to do with your last pull request. I'll look into it a bit later if you need help.

**Comment by Noumanmufc1** [comment]
I copied the code from the original repository and the error still didn't go away

**Comment by ad71** [comment]
I'll look into this later today.

**Comment by ad71** [comment]
This has now been fixed in #867 . Thanks for pointing it out.
