### ISSUE TITLE
'TrivialVacuumEnvironment' object is not callable

### ISSUE THREAD

**Issue by snigdharao28** [aimacode/aima-python#870]
Can someone please explain why in the test_agents.py file, under the test_compare_agents() function, we are not creating an "environment" object of the class TrivialVacuumEnvironment? The code is as follows:
def test_compare_agents() :
    environment = TrivialVacuumEnvironment
    agents = [ModelBasedVacuumAgent, ReflexVacuumAgent]

At first, I thought it was a typo, so I did the following modifications
def test_compare_agents() :
    environment = TrivialVacuumEnvironment()
    agents = [ModelBasedVacuumAgent(), ReflexVacuumAgent()]

but the Travis CI build failed for these changes that I had made and the error is as follows.

E   TypeError: 'TrivialVacuumEnvironment' object is not callable

 So I reverted back the changes. It'll be of great help if someone can tell me what is it that I'm missing here. Thanks.

**Comment by apb7** [comment]
Hi @snigdharao28! The `compare_agents` function takes an environment factory or constructor and not an environment object:  
```python
def compare_agents(EnvFactory, AgentFactories, n=10, steps=1000):
    """See how well each of several agents do in n instances of an environment.
    Pass in a factory (constructor) for environments, and several for agents.
    Create n instances of the environment, and run each agent in copies of
    each one for steps. Return a list of (agent, average-score) tuples."""
    envs = [EnvFactory() for i in range(n)]
    return [(A, test_agent(A, steps, copy.deepcopy(envs)))
            for A in AgentFactories]
```
As you can see, it creates an object of the `EnvFactory` in this line:
```python
envs = [EnvFactory() for i in range(n)]
``` 
 and then uses it compare agent performance. Therefore the Travis build fails, stating that Object is not callable.

Hope this helps!
Thanks!

**Comment by kunwar31** [comment]
compare_agents expects a Environment Factory and an Agent Factory to generate objects. It does not expect already created objects as parameters, hence the error.

**Comment by snigdharao28** [comment]
Thanks @apb7 and @kunwar31  for the help!
