### ISSUE TITLE
Adding explanation of N-gram character models in nlp.ipynb 

### ISSUE THREAD

**Issue by ashwinnalwade** [aimacode/aima-python#886]
@norvig and @ad71 , I noticed that a discussion on N-gram character models is missing (in addition to many other key points of interest in the chapters) in nlp.ipynb .Can I add that in there?

**Comment by MrDupin** [comment]
Hello @ashwinnalwade! The explanation on Char/Word models is in [`text.ipynb`](https://github.com/aimacode/aima-python/blob/master/text.ipynb). The difference between the NLP and Text modules is that Text takes care of some basic stuff and NLP using Text to do some more complex stuff.

You are free to add to the sections you mentioned, but they should remain in Text.

**Comment by ashwinnalwade** [comment]
@MrDupin Thanks for the clarification.I will work on it.
