### ISSUE TITLE
Errors in search notebook due to refactoring

### ISSUE THREAD

**Issue by nvinayvarma189** [aimacode/aima-python#901]
in #878 FIFOQueue, Stack and PriorityQueue are refactored and changes were made to `search.py`. The changes are not made in the search notebook. This causes errors in the graph visualizations like `FIFOQueue not defined`, `Stack not defined` etc. The code in the notebook needs to be updated with the code in `search.py`

**Comment by MrDupin** [comment]
Nice catch! I have added the 'help wanted' label so that others can contribute to this.

**Comment by nvinayvarma189** [comment]
I have submitted PR #902. can you review that @MrDupin?  Thanks

**Comment by MrDupin** [comment]
I'm afraid I am not familiar with that part of the `search` module, so I can't be of much help.

**Comment by ad71** [comment]
This issue can be closed. #902 has been merged.
