### ISSUE TITLE
Planning Notebook: Air Cargo and Spare Tire Problems

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#907]
In the `planning` notebook, the Air Cargo and Spare Tire Problems are not explained very well. The problem statements are not as clear as they could be. They need to be explained in a bit more detail, so that readers can easily understand what is going on without having the book right by their side, going back and forth between book and notebook.

So, I suggest the introduction to these problems is fleshed out a bit more. There is no need for long paragraphs, just a short one like the Three Block Tower Problem will do.

**Comment by nvinayvarma189** [comment]
I would like to work on this. I will add more information to the required sections. I will make sure that it will provide a clear idea for a student who refers to the notebook.
