### ISSUE TITLE
Error in learning_apps notebook

### ISSUE THREAD

**Issue by Noumanmufc1** [aimacode/aima-python#972]
There seems to be an error in the learning_apps notebook. Don't know exactly what is causing that but when the an object of DataSet is initialized with the MNIST or the Fashion MNIST dataset, it gives the following error:
"ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()". Can someone help regarding this?

**Comment by Noumanmufc1** [comment]
@ad71 any idea about this?

**Comment by ad71** [comment]
Sure, it's a minor issue, I'll submit a PR right away.
