### ISSUE TITLE
URLs not working in intro.ipynb notebook

### ISSUE THREAD

**Issue by sagar-sehgal** [aimacode/aima-python#992]
@norvig , @chiragvartak , @MrDupin , @ad71  
In [intro.ipynb](https://github.com/aimacode/aima-python/blob/master/intro.ipynb) notebook in the **What version of Python?** section, 2 URLs are not working. 

1. The link to the [legacy branch](https://github.com/aimacode/aima-python/tree/aima3python2) gives 404 error. 
2.  The link to [Anaconda](https://www.continuum.io/downloads) is also not accessible. The link of Anaconda has been modified  to https://www.anaconda.com/download/ .

**Comment by MrDupin** [comment]
Good catch, it's fixed now.

Thanks!
